// ============================================================
// animationsystem.kt
// Auto-generated by source2offset; do not edit manually
// ============================================================

package org.kvxd.source2offset.offsets

import org.kvxd.unsafeKt.UnsafeKt
import org.kvxd.unsafeKt.mem.Struct

/**
 * Reflected schema data for libanimationsystem.so.
 *
 * Offset namespaces contain fields declared directly on each reflected class.
 * Struct wrappers deliberately do not inherit: the dump proves parent relationships,
 * but does not assume a universal native base-subobject displacement rule.
 * Fields with unknown value layout retain an Address accessor instead of an unsafe decoder.
 */
object AnimationsystemSchema {

    /** Fields declared directly by CBasePulseGraphInstance. */
    object CBasePulseGraphInstance {
        const val SCHEMA_NAME: String = "CBasePulseGraphInstance"
    }

    /** Read/write view of decodable fields declared directly by CBasePulseGraphInstance.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CBasePulseGraphInstanceStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by CParticleBindingRealPulse. Reflected parent: CParticleCollectionBindingInstance. */
    object CParticleBindingRealPulse {
        const val SCHEMA_NAME: String = "CParticleBindingRealPulse"
        const val PARENT_SCHEMA_NAME: String = "CParticleCollectionBindingInstance"
    }

    /** Read/write view of decodable fields declared directly by CParticleBindingRealPulse.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CParticleBindingRealPulseStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by CParticleCollectionBindingInstance. Reflected parent: CBasePulseGraphInstance. */
    object CParticleCollectionBindingInstance {
        const val SCHEMA_NAME: String = "CParticleCollectionBindingInstance"
        const val PARENT_SCHEMA_NAME: String = "CBasePulseGraphInstance"
    }

    /** Read/write view of decodable fields declared directly by CParticleCollectionBindingInstance.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CParticleCollectionBindingInstanceStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by CPulseArraylib. */
    object CPulseArraylib {
        const val SCHEMA_NAME: String = "CPulseArraylib"
    }

    /** Read/write view of decodable fields declared directly by CPulseArraylib.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseArraylibStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by CPulseCell_Base. */
    object CPulseCell_Base {
        const val SCHEMA_NAME: String = "CPulseCell_Base"
        const val m_nEditorNodeID: Long = 0x8L // PulseDocNodeID_t; schema=m_nEditorNodeID
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_Base.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_BaseStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_nEditorNodeID: PulseDocNodeID_t; no safe value decoder was proven. */
        val m_nEditorNodeIDAddress: Long get() = base + CPulseCell_Base.m_nEditorNodeID
    }

    /** Fields declared directly by CPulseCell_BaseFlow. Reflected parent: CPulseCell_Base. */
    object CPulseCell_BaseFlow {
        const val SCHEMA_NAME: String = "CPulseCell_BaseFlow"
        const val PARENT_SCHEMA_NAME: String = "CPulseCell_Base"
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_BaseFlow.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_BaseFlowStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by CPulseCell_BaseLerp. Reflected parent: CPulseCell_BaseYieldingInflow. */
    object CPulseCell_BaseLerp {
        const val SCHEMA_NAME: String = "CPulseCell_BaseLerp"
        const val PARENT_SCHEMA_NAME: String = "CPulseCell_BaseYieldingInflow"
        const val m_WakeResume: Long = 0x48L // CPulse_ResumePoint; schema=m_WakeResume
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_BaseLerp.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_BaseLerpStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_WakeResume: CPulse_ResumePoint; no safe value decoder was proven. */
        val m_WakeResumeAddress: Long get() = base + CPulseCell_BaseLerp.m_WakeResume
    }

    /** Fields declared directly by CPulseCell_BaseRequirement. Reflected parent: CPulseCell_Base. */
    object CPulseCell_BaseRequirement {
        const val SCHEMA_NAME: String = "CPulseCell_BaseRequirement"
        const val PARENT_SCHEMA_NAME: String = "CPulseCell_Base"
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_BaseRequirement.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_BaseRequirementStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by CPulseCell_BaseValue. Reflected parent: CPulseCell_Base. */
    object CPulseCell_BaseValue {
        const val SCHEMA_NAME: String = "CPulseCell_BaseValue"
        const val PARENT_SCHEMA_NAME: String = "CPulseCell_Base"
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_BaseValue.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_BaseValueStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by CPulseCell_BaseYieldingInflow. Reflected parent: CPulseCell_BaseFlow. */
    object CPulseCell_BaseYieldingInflow {
        const val SCHEMA_NAME: String = "CPulseCell_BaseYieldingInflow"
        const val PARENT_SCHEMA_NAME: String = "CPulseCell_BaseFlow"
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_BaseYieldingInflow.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_BaseYieldingInflowStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by CPulseCell_Inflow_BaseEntrypoint. Reflected parent: CPulseCell_BaseFlow. */
    object CPulseCell_Inflow_BaseEntrypoint {
        const val SCHEMA_NAME: String = "CPulseCell_Inflow_BaseEntrypoint"
        const val PARENT_SCHEMA_NAME: String = "CPulseCell_BaseFlow"
        const val m_EntryChunk: Long = 0x48L // PulseRuntimeChunkIndex_t; schema=m_EntryChunk
        const val m_RegisterMap: Long = 0x50L // PulseRegisterMap_t; schema=m_RegisterMap
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_Inflow_BaseEntrypoint.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_Inflow_BaseEntrypointStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_EntryChunk: PulseRuntimeChunkIndex_t; no safe value decoder was proven. */
        val m_EntryChunkAddress: Long get() = base + CPulseCell_Inflow_BaseEntrypoint.m_EntryChunk
        /** Raw address of m_RegisterMap: PulseRegisterMap_t; no safe value decoder was proven. */
        val m_RegisterMapAddress: Long get() = base + CPulseCell_Inflow_BaseEntrypoint.m_RegisterMap
    }

    /** Fields declared directly by CPulseCell_Inflow_EntOutputHandler. Reflected parent: CPulseCell_Inflow_BaseEntrypoint. */
    object CPulseCell_Inflow_EntOutputHandler {
        const val SCHEMA_NAME: String = "CPulseCell_Inflow_EntOutputHandler"
        const val PARENT_SCHEMA_NAME: String = "CPulseCell_Inflow_BaseEntrypoint"
        const val m_SourceEntity: Long = 0x80L // PulseSymbol_t; schema=m_SourceEntity
        const val m_SourceOutput: Long = 0x90L // PulseSymbol_t; schema=m_SourceOutput
        const val m_ExpectedParamType: Long = 0xA0L // CPulseValueFullType; schema=m_ExpectedParamType
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_Inflow_EntOutputHandler.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_Inflow_EntOutputHandlerStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_SourceEntity: PulseSymbol_t; no safe value decoder was proven. */
        val m_SourceEntityAddress: Long get() = base + CPulseCell_Inflow_EntOutputHandler.m_SourceEntity
        /** Raw address of m_SourceOutput: PulseSymbol_t; no safe value decoder was proven. */
        val m_SourceOutputAddress: Long get() = base + CPulseCell_Inflow_EntOutputHandler.m_SourceOutput
        /** Raw address of m_ExpectedParamType: CPulseValueFullType; no safe value decoder was proven. */
        val m_ExpectedParamTypeAddress: Long get() = base + CPulseCell_Inflow_EntOutputHandler.m_ExpectedParamType
    }

    /** Fields declared directly by CPulseCell_Inflow_EventHandler. Reflected parent: CPulseCell_Inflow_BaseEntrypoint. */
    object CPulseCell_Inflow_EventHandler {
        const val SCHEMA_NAME: String = "CPulseCell_Inflow_EventHandler"
        const val PARENT_SCHEMA_NAME: String = "CPulseCell_Inflow_BaseEntrypoint"
        const val m_EventName: Long = 0x80L // PulseSymbol_t; schema=m_EventName
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_Inflow_EventHandler.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_Inflow_EventHandlerStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_EventName: PulseSymbol_t; no safe value decoder was proven. */
        val m_EventNameAddress: Long get() = base + CPulseCell_Inflow_EventHandler.m_EventName
    }

    /** Fields declared directly by CPulseCell_Inflow_GraphHook. Reflected parent: CPulseCell_Inflow_BaseEntrypoint. */
    object CPulseCell_Inflow_GraphHook {
        const val SCHEMA_NAME: String = "CPulseCell_Inflow_GraphHook"
        const val PARENT_SCHEMA_NAME: String = "CPulseCell_Inflow_BaseEntrypoint"
        const val m_HookName: Long = 0x80L // PulseSymbol_t; schema=m_HookName
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_Inflow_GraphHook.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_Inflow_GraphHookStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_HookName: PulseSymbol_t; no safe value decoder was proven. */
        val m_HookNameAddress: Long get() = base + CPulseCell_Inflow_GraphHook.m_HookName
    }

    /** Fields declared directly by CPulseCell_Inflow_ObservableVariableListener. Reflected parent: CPulseCell_Inflow_BaseEntrypoint. */
    object CPulseCell_Inflow_ObservableVariableListener {
        const val SCHEMA_NAME: String = "CPulseCell_Inflow_ObservableVariableListener"
        const val PARENT_SCHEMA_NAME: String = "CPulseCell_Inflow_BaseEntrypoint"
        const val m_nBlackboardReference: Long = 0x80L // PulseRuntimeBlackboardReferenceIndex_t; schema=m_nBlackboardReference
        const val m_bSelfReference: Long = 0x82L // bool; schema=m_bSelfReference
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_Inflow_ObservableVariableListener.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_Inflow_ObservableVariableListenerStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_nBlackboardReference: PulseRuntimeBlackboardReferenceIndex_t; no safe value decoder was proven. */
        val m_nBlackboardReferenceAddress: Long get() = base + CPulseCell_Inflow_ObservableVariableListener.m_nBlackboardReference
        var m_bSelfReference: Boolean by bool(CPulseCell_Inflow_ObservableVariableListener.m_bSelfReference)
    }

    /** Fields declared directly by CPulseCell_IntervalTimer. Reflected parent: CPulseCell_BaseYieldingInflow. */
    object CPulseCell_IntervalTimer {
        const val SCHEMA_NAME: String = "CPulseCell_IntervalTimer"
        const val PARENT_SCHEMA_NAME: String = "CPulseCell_BaseYieldingInflow"
        const val m_Completed: Long = 0x48L // CPulse_ResumePoint; schema=m_Completed
        const val m_OnInterval: Long = 0x90L // SignatureOutflow_Continue; schema=m_OnInterval
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_IntervalTimer.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_IntervalTimerStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_Completed: CPulse_ResumePoint; no safe value decoder was proven. */
        val m_CompletedAddress: Long get() = base + CPulseCell_IntervalTimer.m_Completed
        /** Raw address of m_OnInterval: SignatureOutflow_Continue; no safe value decoder was proven. */
        val m_OnIntervalAddress: Long get() = base + CPulseCell_IntervalTimer.m_OnInterval
    }

    /** Fields declared directly by CPulseCell_IntervalTimer::CursorState_t. */
    object CPulseCell_IntervalTimer__CursorState_t {
        const val SCHEMA_NAME: String = "CPulseCell_IntervalTimer::CursorState_t"
        const val m_StartTime: Long = 0x0L // GameTime_t; schema=m_StartTime
        const val m_EndTime: Long = 0x4L // GameTime_t; schema=m_EndTime
        const val m_flWaitInterval: Long = 0x8L // float32; schema=m_flWaitInterval
        const val m_flWaitIntervalHigh: Long = 0xCL // float32; schema=m_flWaitIntervalHigh
        const val m_bCompleteOnNextWake: Long = 0x10L // bool; schema=m_bCompleteOnNextWake
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_IntervalTimer::CursorState_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_IntervalTimer__CursorState_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_StartTime: GameTime_t; no safe value decoder was proven. */
        val m_StartTimeAddress: Long get() = base + CPulseCell_IntervalTimer__CursorState_t.m_StartTime
        /** Raw address of m_EndTime: GameTime_t; no safe value decoder was proven. */
        val m_EndTimeAddress: Long get() = base + CPulseCell_IntervalTimer__CursorState_t.m_EndTime
        var m_flWaitInterval: Float by float(CPulseCell_IntervalTimer__CursorState_t.m_flWaitInterval)
        var m_flWaitIntervalHigh: Float by float(CPulseCell_IntervalTimer__CursorState_t.m_flWaitIntervalHigh)
        var m_bCompleteOnNextWake: Boolean by bool(CPulseCell_IntervalTimer__CursorState_t.m_bCompleteOnNextWake)
    }

    /** Fields declared directly by CPulseCell_IsRequirementValid. Reflected parent: CPulseCell_BaseRequirement. */
    object CPulseCell_IsRequirementValid {
        const val SCHEMA_NAME: String = "CPulseCell_IsRequirementValid"
        const val PARENT_SCHEMA_NAME: String = "CPulseCell_BaseRequirement"
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_IsRequirementValid.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_IsRequirementValidStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by CPulseCell_IsRequirementValid::Criteria_t. */
    object CPulseCell_IsRequirementValid__Criteria_t {
        const val SCHEMA_NAME: String = "CPulseCell_IsRequirementValid::Criteria_t"
        const val m_bIsValid: Long = 0x0L // bool; schema=m_bIsValid
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_IsRequirementValid::Criteria_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_IsRequirementValid__Criteria_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_bIsValid: Boolean by bool(CPulseCell_IsRequirementValid__Criteria_t.m_bIsValid)
    }

    /** Fields declared directly by CPulseCell_LimitCount::InstanceState_t. */
    object CPulseCell_LimitCount__InstanceState_t {
        const val SCHEMA_NAME: String = "CPulseCell_LimitCount::InstanceState_t"
        const val m_nCurrentCount: Long = 0x0L // int32; schema=m_nCurrentCount
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_LimitCount::InstanceState_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_LimitCount__InstanceState_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_nCurrentCount: Int by int32(CPulseCell_LimitCount__InstanceState_t.m_nCurrentCount)
    }

    /** Fields declared directly by CPulseCell_Timeline. Reflected parent: CPulseCell_BaseYieldingInflow. */
    object CPulseCell_Timeline {
        const val SCHEMA_NAME: String = "CPulseCell_Timeline"
        const val PARENT_SCHEMA_NAME: String = "CPulseCell_BaseYieldingInflow"
        const val m_TimelineEvents: Long = 0x48L // CUtlVector<CPulseCell_Timeline::TimelineEvent_t>; schema=m_TimelineEvents
        const val m_bWaitForChildOutflows: Long = 0x60L // bool; schema=m_bWaitForChildOutflows
        const val m_OnFinished: Long = 0x68L // CPulse_ResumePoint; schema=m_OnFinished
        const val m_OnCanceled: Long = 0xB0L // CPulse_ResumePoint; schema=m_OnCanceled
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_Timeline.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_TimelineStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_TimelineEvents: CUtlVector<CPulseCell_Timeline::TimelineEvent_t>; no safe value decoder was proven. */
        val m_TimelineEventsAddress: Long get() = base + CPulseCell_Timeline.m_TimelineEvents
        var m_bWaitForChildOutflows: Boolean by bool(CPulseCell_Timeline.m_bWaitForChildOutflows)
        /** Raw address of m_OnFinished: CPulse_ResumePoint; no safe value decoder was proven. */
        val m_OnFinishedAddress: Long get() = base + CPulseCell_Timeline.m_OnFinished
        /** Raw address of m_OnCanceled: CPulse_ResumePoint; no safe value decoder was proven. */
        val m_OnCanceledAddress: Long get() = base + CPulseCell_Timeline.m_OnCanceled
    }

    /** Fields declared directly by CPulseCell_Value_Curve. Reflected parent: CPulseCell_BaseValue. */
    object CPulseCell_Value_Curve {
        const val SCHEMA_NAME: String = "CPulseCell_Value_Curve"
        const val PARENT_SCHEMA_NAME: String = "CPulseCell_BaseValue"
        const val m_Curve: Long = 0x48L // CPiecewiseCurve; schema=m_Curve
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_Value_Curve.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_Value_CurveStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_Curve: CPiecewiseCurve; no safe value decoder was proven. */
        val m_CurveAddress: Long get() = base + CPulseCell_Value_Curve.m_Curve
    }

    /** Fields declared directly by CPulseCell_WaitForCursorsWithTagBase::CursorState_t. */
    object CPulseCell_WaitForCursorsWithTagBase__CursorState_t {
        const val SCHEMA_NAME: String = "CPulseCell_WaitForCursorsWithTagBase::CursorState_t"
        const val m_TagName: Long = 0x0L // PulseSymbol_t; schema=m_TagName
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_WaitForCursorsWithTagBase::CursorState_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_WaitForCursorsWithTagBase__CursorState_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_TagName: PulseSymbol_t; no safe value decoder was proven. */
        val m_TagNameAddress: Long get() = base + CPulseCell_WaitForCursorsWithTagBase__CursorState_t.m_TagName
    }

    /** Fields declared directly by CPulseCell_WaitForObservable. Reflected parent: CPulseCell_BaseYieldingInflow. */
    object CPulseCell_WaitForObservable {
        const val SCHEMA_NAME: String = "CPulseCell_WaitForObservable"
        const val PARENT_SCHEMA_NAME: String = "CPulseCell_BaseYieldingInflow"
        const val m_Condition: Long = 0x48L // PulseObservableBoolExpression_t; schema=m_Condition
        const val m_OnTrue: Long = 0xC0L // CPulse_ResumePoint; schema=m_OnTrue
    }

    /** Read/write view of decodable fields declared directly by CPulseCell_WaitForObservable.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseCell_WaitForObservableStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_Condition: PulseObservableBoolExpression_t; no safe value decoder was proven. */
        val m_ConditionAddress: Long get() = base + CPulseCell_WaitForObservable.m_Condition
        /** Raw address of m_OnTrue: CPulse_ResumePoint; no safe value decoder was proven. */
        val m_OnTrueAddress: Long get() = base + CPulseCell_WaitForObservable.m_OnTrue
    }

    /** Fields declared directly by CPulseGraphDef. */
    object CPulseGraphDef {
        const val SCHEMA_NAME: String = "CPulseGraphDef"
        const val m_DomainIdentifier: Long = 0x8L // PulseSymbol_t; schema=m_DomainIdentifier
        const val m_DomainSubType: Long = 0x18L // CPulseValueFullType; schema=m_DomainSubType
        const val m_ParentMapName: Long = 0x30L // PulseSymbol_t; schema=m_ParentMapName
        const val m_ParentXmlName: Long = 0x40L // PulseSymbol_t; schema=m_ParentXmlName
        const val m_Chunks: Long = 0x50L // CUtlVector<CPulse_Chunk*>; schema=m_Chunks
        const val m_Cells: Long = 0x68L // CUtlVector<CPulseCell_Base*>; schema=m_Cells
        const val m_Vars: Long = 0x80L // CUtlVector<CPulse_Variable>; schema=m_Vars
        const val m_PublicOutputs: Long = 0x98L // CUtlVector<CPulse_PublicOutput>; schema=m_PublicOutputs
        const val m_InvokeBindings: Long = 0xB0L // CUtlVector<CPulse_InvokeBinding*>; schema=m_InvokeBindings
        const val m_CallInfos: Long = 0xC8L // CUtlVector<CPulse_CallInfo*>; schema=m_CallInfos
        const val m_Constants: Long = 0xE0L // CUtlVector<CPulse_Constant>; schema=m_Constants
        const val m_DomainValues: Long = 0xF8L // CUtlVector<CPulse_DomainValue>; schema=m_DomainValues
        const val m_BlackboardReferences: Long = 0x110L // CUtlVector<CPulse_BlackboardReference>; schema=m_BlackboardReferences
        const val m_OutputConnections: Long = 0x128L // CUtlVector<CPulse_OutputConnection*>; schema=m_OutputConnections
    }

    /** Read/write view of decodable fields declared directly by CPulseGraphDef.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulseGraphDefStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_DomainIdentifier: PulseSymbol_t; no safe value decoder was proven. */
        val m_DomainIdentifierAddress: Long get() = base + CPulseGraphDef.m_DomainIdentifier
        /** Raw address of m_DomainSubType: CPulseValueFullType; no safe value decoder was proven. */
        val m_DomainSubTypeAddress: Long get() = base + CPulseGraphDef.m_DomainSubType
        /** Raw address of m_ParentMapName: PulseSymbol_t; no safe value decoder was proven. */
        val m_ParentMapNameAddress: Long get() = base + CPulseGraphDef.m_ParentMapName
        /** Raw address of m_ParentXmlName: PulseSymbol_t; no safe value decoder was proven. */
        val m_ParentXmlNameAddress: Long get() = base + CPulseGraphDef.m_ParentXmlName
        var m_Chunks: Long by ptr64(CPulseGraphDef.m_Chunks)
        var m_Cells: Long by ptr64(CPulseGraphDef.m_Cells)
        /** Raw address of m_Vars: CUtlVector<CPulse_Variable>; no safe value decoder was proven. */
        val m_VarsAddress: Long get() = base + CPulseGraphDef.m_Vars
        /** Raw address of m_PublicOutputs: CUtlVector<CPulse_PublicOutput>; no safe value decoder was proven. */
        val m_PublicOutputsAddress: Long get() = base + CPulseGraphDef.m_PublicOutputs
        var m_InvokeBindings: Long by ptr64(CPulseGraphDef.m_InvokeBindings)
        var m_CallInfos: Long by ptr64(CPulseGraphDef.m_CallInfos)
        /** Raw address of m_Constants: CUtlVector<CPulse_Constant>; no safe value decoder was proven. */
        val m_ConstantsAddress: Long get() = base + CPulseGraphDef.m_Constants
        /** Raw address of m_DomainValues: CUtlVector<CPulse_DomainValue>; no safe value decoder was proven. */
        val m_DomainValuesAddress: Long get() = base + CPulseGraphDef.m_DomainValues
        /** Raw address of m_BlackboardReferences: CUtlVector<CPulse_BlackboardReference>; no safe value decoder was proven. */
        val m_BlackboardReferencesAddress: Long get() = base + CPulseGraphDef.m_BlackboardReferences
        var m_OutputConnections: Long by ptr64(CPulseGraphDef.m_OutputConnections)
    }

    /** Fields declared directly by CPulse_InvokeBinding. */
    object CPulse_InvokeBinding {
        const val SCHEMA_NAME: String = "CPulse_InvokeBinding"
        const val m_RegisterMap: Long = 0x0L // PulseRegisterMap_t; schema=m_RegisterMap
        const val m_FuncName: Long = 0x30L // PulseSymbol_t; schema=m_FuncName
        const val m_nCellIndex: Long = 0x40L // PulseRuntimeCellIndex_t; schema=m_nCellIndex
        const val m_nSrcChunk: Long = 0x44L // PulseRuntimeChunkIndex_t; schema=m_nSrcChunk
        const val m_nSrcInstruction: Long = 0x48L // int32; schema=m_nSrcInstruction
    }

    /** Read/write view of decodable fields declared directly by CPulse_InvokeBinding.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulse_InvokeBindingStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_RegisterMap: PulseRegisterMap_t; no safe value decoder was proven. */
        val m_RegisterMapAddress: Long get() = base + CPulse_InvokeBinding.m_RegisterMap
        /** Raw address of m_FuncName: PulseSymbol_t; no safe value decoder was proven. */
        val m_FuncNameAddress: Long get() = base + CPulse_InvokeBinding.m_FuncName
        /** Raw address of m_nCellIndex: PulseRuntimeCellIndex_t; no safe value decoder was proven. */
        val m_nCellIndexAddress: Long get() = base + CPulse_InvokeBinding.m_nCellIndex
        /** Raw address of m_nSrcChunk: PulseRuntimeChunkIndex_t; no safe value decoder was proven. */
        val m_nSrcChunkAddress: Long get() = base + CPulse_InvokeBinding.m_nSrcChunk
        var m_nSrcInstruction: Int by int32(CPulse_InvokeBinding.m_nSrcInstruction)
    }

    /** Fields declared directly by CPulse_OutflowConnection. */
    object CPulse_OutflowConnection {
        const val SCHEMA_NAME: String = "CPulse_OutflowConnection"
        const val m_SourceOutflowName: Long = 0x0L // PulseSymbol_t; schema=m_SourceOutflowName
        const val m_nDestChunk: Long = 0x10L // PulseRuntimeChunkIndex_t; schema=m_nDestChunk
        const val m_nInstruction: Long = 0x14L // int32; schema=m_nInstruction
        const val m_OutflowRegisterMap: Long = 0x18L // PulseRegisterMap_t; schema=m_OutflowRegisterMap
    }

    /** Read/write view of decodable fields declared directly by CPulse_OutflowConnection.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CPulse_OutflowConnectionStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_SourceOutflowName: PulseSymbol_t; no safe value decoder was proven. */
        val m_SourceOutflowNameAddress: Long get() = base + CPulse_OutflowConnection.m_SourceOutflowName
        /** Raw address of m_nDestChunk: PulseRuntimeChunkIndex_t; no safe value decoder was proven. */
        val m_nDestChunkAddress: Long get() = base + CPulse_OutflowConnection.m_nDestChunk
        var m_nInstruction: Int by int32(CPulse_OutflowConnection.m_nInstruction)
        /** Raw address of m_OutflowRegisterMap: PulseRegisterMap_t; no safe value decoder was proven. */
        val m_OutflowRegisterMapAddress: Long get() = base + CPulse_OutflowConnection.m_OutflowRegisterMap
    }

    /** Fields declared directly by PulseNodeDynamicOutflows_t. */
    object PulseNodeDynamicOutflows_t {
        const val SCHEMA_NAME: String = "PulseNodeDynamicOutflows_t"
        const val m_Outflows: Long = 0x0L // CUtlVector<PulseNodeDynamicOutflows_t::DynamicOutflow_t>; schema=m_Outflows
    }

    /** Read/write view of decodable fields declared directly by PulseNodeDynamicOutflows_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class PulseNodeDynamicOutflows_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_Outflows: CUtlVector<PulseNodeDynamicOutflows_t::DynamicOutflow_t>; no safe value decoder was proven. */
        val m_OutflowsAddress: Long get() = base + PulseNodeDynamicOutflows_t.m_Outflows
    }

    /** Fields declared directly by PulseNodeDynamicOutflows_t::DynamicOutflow_t. */
    object PulseNodeDynamicOutflows_t__DynamicOutflow_t {
        const val SCHEMA_NAME: String = "PulseNodeDynamicOutflows_t::DynamicOutflow_t"
        const val m_OutflowID: Long = 0x0L // CGlobalSymbol; schema=m_OutflowID
        const val m_Connection: Long = 0x8L // CPulse_OutflowConnection; schema=m_Connection
    }

    /** Read/write view of decodable fields declared directly by PulseNodeDynamicOutflows_t::DynamicOutflow_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class PulseNodeDynamicOutflows_t__DynamicOutflow_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_OutflowID: CGlobalSymbol; no safe value decoder was proven. */
        val m_OutflowIDAddress: Long get() = base + PulseNodeDynamicOutflows_t__DynamicOutflow_t.m_OutflowID
        /** Embedded reflected value: CPulse_OutflowConnection. */
        val m_Connection: AnimationsystemSchema.CPulse_OutflowConnectionStruct
            get() = AnimationsystemSchema.CPulse_OutflowConnectionStruct(base + PulseNodeDynamicOutflows_t__DynamicOutflow_t.m_Connection, mem)
    }

    /** Fields declared directly by PulseSelectorOutflowList_t. */
    object PulseSelectorOutflowList_t {
        const val SCHEMA_NAME: String = "PulseSelectorOutflowList_t"
        const val m_Outflows: Long = 0x0L // CUtlVector<OutflowWithRequirements_t>; schema=m_Outflows
    }

    /** Read/write view of decodable fields declared directly by PulseSelectorOutflowList_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class PulseSelectorOutflowList_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_Outflows: CUtlVector<OutflowWithRequirements_t>; no safe value decoder was proven. */
        val m_OutflowsAddress: Long get() = base + PulseSelectorOutflowList_t.m_Outflows
    }

    object Enums {
        object CAnimationLayer {
            const val SCHEMA_NAME: String = "CAnimationLayer"
        }

        object CPulseCell_BooleanSwitchState {
            const val SCHEMA_NAME: String = "CPulseCell_BooleanSwitchState"
        }

        object CPulseCell_CursorQueue {
            const val SCHEMA_NAME: String = "CPulseCell_CursorQueue"
        }

        object CPulseCell_Inflow_Method {
            const val SCHEMA_NAME: String = "CPulseCell_Inflow_Method"
        }

        object CPulseCell_Inflow_Wait {
            const val SCHEMA_NAME: String = "CPulseCell_Inflow_Wait"
        }

        object CPulseCell_Outflow_CycleShuffled {
            const val SCHEMA_NAME: String = "CPulseCell_Outflow_CycleShuffled"
        }

        object CPulseCell_Value_RandomFloat {
            const val SCHEMA_NAME: String = "CPulseCell_Value_RandomFloat"
        }

        object CPulseExecCursor {
            const val SCHEMA_NAME: String = "CPulseExecCursor"
        }

        object CPulse_CallInfo {
            const val SCHEMA_NAME: String = "CPulse_CallInfo"
        }

        object ParticleSetMethod_t {
            const val SCHEMA_NAME: String = "ParticleSetMethod_t"
            const val PARTICLE_SET_ADD_TO_CURRENT_VALUE: Long = 5L
            const val PARTICLE_SET_ADD_TO_INITIAL_VALUE: Long = 2L
            const val PARTICLE_SET_RAMP_CURRENT_VALUE: Long = 3L
            const val PARTICLE_SET_REPLACE_VALUE: Long = 0L
            const val PARTICLE_SET_SCALE_CURRENT_VALUE: Long = 4L
            const val PARTICLE_SET_SCALE_INITIAL_VALUE: Long = 1L
        }

        object PulseBestOutflowRules_t {
            const val SCHEMA_NAME: String = "PulseBestOutflowRules_t"
            const val SORT_BY_NUMBER_OF_VALID_CRITERIA: Long = 0L
            const val SORT_BY_OUTFLOW_INDEX: Long = 1L
        }

        object PulseObservableBoolExpression_t {
            const val SCHEMA_NAME: String = "PulseObservableBoolExpression_t"
        }

    }
}
