// ============================================================
// host.kt
// Auto-generated by source2offset; do not edit manually
// ============================================================

package org.kvxd.source2offset.offsets

import org.kvxd.unsafeKt.UnsafeKt
import org.kvxd.unsafeKt.mem.Struct

object HostSchema {

    /** Fields declared directly by CAnimScriptBase. */
    object CAnimScriptBase {
        const val SCHEMA_NAME: String = "CAnimScriptBase"
        const val m_bIsValid: Long = 0x8L // bool; schema=m_bIsValid
    }

    class CAnimScriptBaseStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_bIsValid: Boolean by bool(CAnimScriptBase.m_bIsValid)
    }

    /** Fields declared directly by EmptyTestScript. Reflected parent: CAnimScriptBase. */
    object EmptyTestScript {
        const val SCHEMA_NAME: String = "EmptyTestScript"
        const val PARENT_SCHEMA_NAME: String = "CAnimScriptBase"
        const val m_hTest: Long = 0x10L // CAnimScriptParam<float32>; schema=m_hTest
    }

    class EmptyTestScriptStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_hTest: CAnimScriptParam<float32>; no safe value decoder was proven. */
        val m_hTestAddress: Long get() = base + EmptyTestScript.m_hTest
    }

    /** Fields declared directly by k_EGCMsgWebAPIJobRequest. */
    object k_EGCMsgWebAPIJobRequest {
        const val SCHEMA_NAME: String = "k_EGCMsgWebAPIJobRequest"
    }

    class k_EGCMsgWebAPIJobRequestStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

}
