// ============================================================
// interfaces.kt
// Auto-generated by source2offset; do not edit manually
// ============================================================

package org.kvxd.source2offset.offsets

object client_Interfaces {
    const val Source2ClientPrediction001: Long = 0x467BD00L
}

object engine2_Interfaces {
    const val GameResourceServiceClientV001: Long = 0x9C3B20L
}

object inputsystem_Interfaces {
    const val InputSystemVersion001: Long = 0x7EFE0L
}

object schemasystem_Interfaces {
    const val SchemaSystem_001: Long = 0xB5DA0L
}

object soundsystem_Interfaces {
    const val SoundSystem001: Long = 0x75BA00L
}

