// ============================================================
// materialsystem2.kt
// Auto-generated by source2offset; do not edit manually
// ============================================================

package org.kvxd.source2offset.offsets

import org.kvxd.unsafeKt.UnsafeKt
import org.kvxd.unsafeKt.mem.Struct

/**
 * Reflected schema data for libmaterialsystem2.so.
 *
 * Offset namespaces contain fields declared directly on each reflected class.
 * Struct wrappers deliberately do not inherit: the dump proves parent relationships,
 * but does not assume a universal native base-subobject displacement rule.
 * Fields with unknown value layout retain an Address accessor instead of an unsafe decoder.
 */
object Materialsystem2Schema {

    /** Fields declared directly by MaterialParamBuffer_t. Reflected parent: MaterialParam_t. */
    object MaterialParamBuffer_t {
        const val SCHEMA_NAME: String = "MaterialParamBuffer_t"
        const val PARENT_SCHEMA_NAME: String = "MaterialParam_t"
        const val m_value: Long = 0x8L // CUtlBinaryBlock; schema=m_value
    }

    /** Read/write view of decodable fields declared directly by MaterialParamBuffer_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class MaterialParamBuffer_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_value: CUtlBinaryBlock; no safe value decoder was proven. */
        val m_valueAddress: Long get() = base + MaterialParamBuffer_t.m_value
    }

    /** Fields declared directly by MaterialParamFloat_t. Reflected parent: MaterialParam_t. */
    object MaterialParamFloat_t {
        const val SCHEMA_NAME: String = "MaterialParamFloat_t"
        const val PARENT_SCHEMA_NAME: String = "MaterialParam_t"
        const val m_flValue: Long = 0x8L // float32; schema=m_flValue
    }

    /** Read/write view of decodable fields declared directly by MaterialParamFloat_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class MaterialParamFloat_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_flValue: Float by float(MaterialParamFloat_t.m_flValue)
    }

    /** Fields declared directly by MaterialParamInt_t. Reflected parent: MaterialParam_t. */
    object MaterialParamInt_t {
        const val SCHEMA_NAME: String = "MaterialParamInt_t"
        const val PARENT_SCHEMA_NAME: String = "MaterialParam_t"
        const val m_nValue: Long = 0x8L // int32; schema=m_nValue
    }

    /** Read/write view of decodable fields declared directly by MaterialParamInt_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class MaterialParamInt_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_nValue: Int by int32(MaterialParamInt_t.m_nValue)
    }

    /** Fields declared directly by MaterialParamString_t. Reflected parent: MaterialParam_t. */
    object MaterialParamString_t {
        const val SCHEMA_NAME: String = "MaterialParamString_t"
        const val PARENT_SCHEMA_NAME: String = "MaterialParam_t"
        const val m_value: Long = 0x8L // CUtlString; schema=m_value
    }

    /** Read/write view of decodable fields declared directly by MaterialParamString_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class MaterialParamString_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_value: Long by ptr64(MaterialParamString_t.m_value)
    }

    /** Fields declared directly by MaterialParamTexture_t. Reflected parent: MaterialParam_t. */
    object MaterialParamTexture_t {
        const val SCHEMA_NAME: String = "MaterialParamTexture_t"
        const val PARENT_SCHEMA_NAME: String = "MaterialParam_t"
        const val m_pValue: Long = 0x8L // CStrongHandle<InfoForResourceTypeCTextureBase>; schema=m_pValue
    }

    /** Read/write view of decodable fields declared directly by MaterialParamTexture_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class MaterialParamTexture_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_pValue: CStrongHandle<InfoForResourceTypeCTextureBase>; no safe value decoder was proven. */
        val m_pValueAddress: Long get() = base + MaterialParamTexture_t.m_pValue
    }

    /** Fields declared directly by MaterialParamVector_t. Reflected parent: MaterialParam_t. */
    object MaterialParamVector_t {
        const val SCHEMA_NAME: String = "MaterialParamVector_t"
        const val PARENT_SCHEMA_NAME: String = "MaterialParam_t"
        const val m_value: Long = 0x8L // Vector4D; schema=m_value
    }

    /** Read/write view of decodable fields declared directly by MaterialParamVector_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class MaterialParamVector_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_value: Vector4D; no safe value decoder was proven. */
        val m_valueAddress: Long get() = base + MaterialParamVector_t.m_value
    }

    /** Fields declared directly by MaterialParam_t. */
    object MaterialParam_t {
        const val SCHEMA_NAME: String = "MaterialParam_t"
        const val m_name: Long = 0x0L // CUtlString; schema=m_name
    }

    /** Read/write view of decodable fields declared directly by MaterialParam_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class MaterialParam_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_name: Long by ptr64(MaterialParam_t.m_name)
    }

    /** Fields declared directly by MaterialResourceData_t. */
    object MaterialResourceData_t {
        const val SCHEMA_NAME: String = "MaterialResourceData_t"
        const val m_materialName: Long = 0x0L // CUtlString; schema=m_materialName
        const val m_shaderName: Long = 0x8L // CUtlString; schema=m_shaderName
        const val m_intParams: Long = 0x10L // CUtlVector<MaterialParamInt_t>; schema=m_intParams
        const val m_floatParams: Long = 0x28L // CUtlVector<MaterialParamFloat_t>; schema=m_floatParams
        const val m_vectorParams: Long = 0x40L // CUtlVector<MaterialParamVector_t>; schema=m_vectorParams
        const val m_textureParams: Long = 0x58L // CUtlVector<MaterialParamTexture_t>; schema=m_textureParams
        const val m_dynamicParams: Long = 0x70L // CUtlVector<MaterialParamBuffer_t>; schema=m_dynamicParams
        const val m_dynamicTextureParams: Long = 0x88L // CUtlVector<MaterialParamBuffer_t>; schema=m_dynamicTextureParams
        const val m_intAttributes: Long = 0xA0L // CUtlVector<MaterialParamInt_t>; schema=m_intAttributes
        const val m_floatAttributes: Long = 0xB8L // CUtlVector<MaterialParamFloat_t>; schema=m_floatAttributes
        const val m_vectorAttributes: Long = 0xD0L // CUtlVector<MaterialParamVector_t>; schema=m_vectorAttributes
        const val m_textureAttributes: Long = 0xE8L // CUtlVector<MaterialParamTexture_t>; schema=m_textureAttributes
        const val m_stringAttributes: Long = 0x100L // CUtlVector<MaterialParamString_t>; schema=m_stringAttributes
        const val m_renderAttributesUsed: Long = 0x118L // CUtlVector<CUtlString>; schema=m_renderAttributesUsed
    }

    /** Read/write view of decodable fields declared directly by MaterialResourceData_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class MaterialResourceData_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_materialName: Long by ptr64(MaterialResourceData_t.m_materialName)
        var m_shaderName: Long by ptr64(MaterialResourceData_t.m_shaderName)
        /** Raw address of m_intParams: CUtlVector<MaterialParamInt_t>; no safe value decoder was proven. */
        val m_intParamsAddress: Long get() = base + MaterialResourceData_t.m_intParams
        /** Raw address of m_floatParams: CUtlVector<MaterialParamFloat_t>; no safe value decoder was proven. */
        val m_floatParamsAddress: Long get() = base + MaterialResourceData_t.m_floatParams
        /** Raw address of m_vectorParams: CUtlVector<MaterialParamVector_t>; no safe value decoder was proven. */
        val m_vectorParamsAddress: Long get() = base + MaterialResourceData_t.m_vectorParams
        /** Raw address of m_textureParams: CUtlVector<MaterialParamTexture_t>; no safe value decoder was proven. */
        val m_textureParamsAddress: Long get() = base + MaterialResourceData_t.m_textureParams
        /** Raw address of m_dynamicParams: CUtlVector<MaterialParamBuffer_t>; no safe value decoder was proven. */
        val m_dynamicParamsAddress: Long get() = base + MaterialResourceData_t.m_dynamicParams
        /** Raw address of m_dynamicTextureParams: CUtlVector<MaterialParamBuffer_t>; no safe value decoder was proven. */
        val m_dynamicTextureParamsAddress: Long get() = base + MaterialResourceData_t.m_dynamicTextureParams
        /** Raw address of m_intAttributes: CUtlVector<MaterialParamInt_t>; no safe value decoder was proven. */
        val m_intAttributesAddress: Long get() = base + MaterialResourceData_t.m_intAttributes
        /** Raw address of m_floatAttributes: CUtlVector<MaterialParamFloat_t>; no safe value decoder was proven. */
        val m_floatAttributesAddress: Long get() = base + MaterialResourceData_t.m_floatAttributes
        /** Raw address of m_vectorAttributes: CUtlVector<MaterialParamVector_t>; no safe value decoder was proven. */
        val m_vectorAttributesAddress: Long get() = base + MaterialResourceData_t.m_vectorAttributes
        /** Raw address of m_textureAttributes: CUtlVector<MaterialParamTexture_t>; no safe value decoder was proven. */
        val m_textureAttributesAddress: Long get() = base + MaterialResourceData_t.m_textureAttributes
        /** Raw address of m_stringAttributes: CUtlVector<MaterialParamString_t>; no safe value decoder was proven. */
        val m_stringAttributesAddress: Long get() = base + MaterialResourceData_t.m_stringAttributes
        /** Raw address of m_renderAttributesUsed: CUtlVector<CUtlString>; no safe value decoder was proven. */
        val m_renderAttributesUsedAddress: Long get() = base + MaterialResourceData_t.m_renderAttributesUsed
    }

    /** Fields declared directly by PostProcessingBloomParameters_t. */
    object PostProcessingBloomParameters_t {
        const val SCHEMA_NAME: String = "PostProcessingBloomParameters_t"
        const val m_blendMode: Long = 0x0L // BloomBlendMode_t; schema=m_blendMode
        const val m_flBloomStrength: Long = 0x4L // float32; schema=m_flBloomStrength
        const val m_flScreenBloomStrength: Long = 0x8L // float32; schema=m_flScreenBloomStrength
        const val m_flBlurBloomStrength: Long = 0xCL // float32; schema=m_flBlurBloomStrength
        const val m_flBloomThreshold: Long = 0x10L // float32; schema=m_flBloomThreshold
        const val m_flBloomThresholdWidth: Long = 0x14L // float32; schema=m_flBloomThresholdWidth
        const val m_flSkyboxBloomStrength: Long = 0x18L // float32; schema=m_flSkyboxBloomStrength
        const val m_flBloomStartValue: Long = 0x1CL // float32; schema=m_flBloomStartValue
        const val m_flComputeBloomStrength: Long = 0x20L // float32; schema=m_flComputeBloomStrength
        const val m_flComputeBloomThreshold: Long = 0x24L // float32; schema=m_flComputeBloomThreshold
        const val m_flComputeBloomRadius: Long = 0x28L // float32; schema=m_flComputeBloomRadius
        const val m_flComputeBloomEffectsScale: Long = 0x2CL // float32; schema=m_flComputeBloomEffectsScale
        const val m_flComputeBloomLensDirtStrength: Long = 0x30L // float32; schema=m_flComputeBloomLensDirtStrength
        const val m_flComputeBloomLensDirtBlackLevel: Long = 0x34L // float32; schema=m_flComputeBloomLensDirtBlackLevel
        const val m_flBlurWeight: Long = 0x38L // float32[5]; schema=m_flBlurWeight
        const val m_vBlurTint: Long = 0x4CL // Vector[5]; schema=m_vBlurTint
    }

    /** Read/write view of decodable fields declared directly by PostProcessingBloomParameters_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class PostProcessingBloomParameters_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_blendMode: BloomBlendMode_t; no safe value decoder was proven. */
        val m_blendModeAddress: Long get() = base + PostProcessingBloomParameters_t.m_blendMode
        var m_flBloomStrength: Float by float(PostProcessingBloomParameters_t.m_flBloomStrength)
        var m_flScreenBloomStrength: Float by float(PostProcessingBloomParameters_t.m_flScreenBloomStrength)
        var m_flBlurBloomStrength: Float by float(PostProcessingBloomParameters_t.m_flBlurBloomStrength)
        var m_flBloomThreshold: Float by float(PostProcessingBloomParameters_t.m_flBloomThreshold)
        var m_flBloomThresholdWidth: Float by float(PostProcessingBloomParameters_t.m_flBloomThresholdWidth)
        var m_flSkyboxBloomStrength: Float by float(PostProcessingBloomParameters_t.m_flSkyboxBloomStrength)
        var m_flBloomStartValue: Float by float(PostProcessingBloomParameters_t.m_flBloomStartValue)
        var m_flComputeBloomStrength: Float by float(PostProcessingBloomParameters_t.m_flComputeBloomStrength)
        var m_flComputeBloomThreshold: Float by float(PostProcessingBloomParameters_t.m_flComputeBloomThreshold)
        var m_flComputeBloomRadius: Float by float(PostProcessingBloomParameters_t.m_flComputeBloomRadius)
        var m_flComputeBloomEffectsScale: Float by float(PostProcessingBloomParameters_t.m_flComputeBloomEffectsScale)
        var m_flComputeBloomLensDirtStrength: Float by float(PostProcessingBloomParameters_t.m_flComputeBloomLensDirtStrength)
        var m_flComputeBloomLensDirtBlackLevel: Float by float(PostProcessingBloomParameters_t.m_flComputeBloomLensDirtBlackLevel)
        /** Raw address of m_flBlurWeight: float32[5]; no safe value decoder was proven. */
        val m_flBlurWeightAddress: Long get() = base + PostProcessingBloomParameters_t.m_flBlurWeight
        /** Raw address of m_vBlurTint: Vector[5]; no safe value decoder was proven. */
        val m_vBlurTintAddress: Long get() = base + PostProcessingBloomParameters_t.m_vBlurTint
    }

    /** Fields declared directly by PostProcessingFogScatteringParameters_t. */
    object PostProcessingFogScatteringParameters_t {
        const val SCHEMA_NAME: String = "PostProcessingFogScatteringParameters_t"
        const val m_fRadius: Long = 0x0L // float32; schema=m_fRadius
        const val m_fScale: Long = 0x4L // float32; schema=m_fScale
        const val m_fCubemapScale: Long = 0x8L // float32; schema=m_fCubemapScale
        const val m_fVolumetricScale: Long = 0xCL // float32; schema=m_fVolumetricScale
        const val m_fGradientScale: Long = 0x10L // float32; schema=m_fGradientScale
    }

    /** Read/write view of decodable fields declared directly by PostProcessingFogScatteringParameters_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class PostProcessingFogScatteringParameters_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_fRadius: Float by float(PostProcessingFogScatteringParameters_t.m_fRadius)
        var m_fScale: Float by float(PostProcessingFogScatteringParameters_t.m_fScale)
        var m_fCubemapScale: Float by float(PostProcessingFogScatteringParameters_t.m_fCubemapScale)
        var m_fVolumetricScale: Float by float(PostProcessingFogScatteringParameters_t.m_fVolumetricScale)
        var m_fGradientScale: Float by float(PostProcessingFogScatteringParameters_t.m_fGradientScale)
    }

    /** Fields declared directly by PostProcessingLocalContrastParameters_t. */
    object PostProcessingLocalContrastParameters_t {
        const val SCHEMA_NAME: String = "PostProcessingLocalContrastParameters_t"
        const val m_flLocalContrastStrength: Long = 0x0L // float32; schema=m_flLocalContrastStrength
        const val m_flLocalContrastEdgeStrength: Long = 0x4L // float32; schema=m_flLocalContrastEdgeStrength
        const val m_flLocalContrastVignetteStart: Long = 0x8L // float32; schema=m_flLocalContrastVignetteStart
        const val m_flLocalContrastVignetteEnd: Long = 0xCL // float32; schema=m_flLocalContrastVignetteEnd
        const val m_flLocalContrastVignetteBlur: Long = 0x10L // float32; schema=m_flLocalContrastVignetteBlur
    }

    /** Read/write view of decodable fields declared directly by PostProcessingLocalContrastParameters_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class PostProcessingLocalContrastParameters_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_flLocalContrastStrength: Float by float(PostProcessingLocalContrastParameters_t.m_flLocalContrastStrength)
        var m_flLocalContrastEdgeStrength: Float by float(PostProcessingLocalContrastParameters_t.m_flLocalContrastEdgeStrength)
        var m_flLocalContrastVignetteStart: Float by float(PostProcessingLocalContrastParameters_t.m_flLocalContrastVignetteStart)
        var m_flLocalContrastVignetteEnd: Float by float(PostProcessingLocalContrastParameters_t.m_flLocalContrastVignetteEnd)
        var m_flLocalContrastVignetteBlur: Float by float(PostProcessingLocalContrastParameters_t.m_flLocalContrastVignetteBlur)
    }

    /** Fields declared directly by PostProcessingResource_t. */
    object PostProcessingResource_t {
        const val SCHEMA_NAME: String = "PostProcessingResource_t"
        const val m_bHasTonemapParams: Long = 0x0L // bool; schema=m_bHasTonemapParams
        const val m_toneMapParams: Long = 0x4L // PostProcessingTonemapParameters_t; schema=m_toneMapParams
        const val m_bHasBloomParams: Long = 0x40L // bool; schema=m_bHasBloomParams
        const val m_bloomParams: Long = 0x44L // PostProcessingBloomParameters_t; schema=m_bloomParams
        const val m_bHasVignetteParams: Long = 0xCCL // bool; schema=m_bHasVignetteParams
        const val m_vignetteParams: Long = 0xD0L // PostProcessingVignetteParameters_t; schema=m_vignetteParams
        const val m_bHasLocalContrastParams: Long = 0xF4L // bool; schema=m_bHasLocalContrastParams
        const val m_localConstrastParams: Long = 0xF8L // PostProcessingLocalContrastParameters_t; schema=m_localConstrastParams
        const val m_nColorCorrectionVolumeDim: Long = 0x10CL // int32; schema=m_nColorCorrectionVolumeDim
        const val m_colorCorrectionVolumeData: Long = 0x110L // CUtlBinaryBlock; schema=m_colorCorrectionVolumeData
        const val m_bHasColorCorrection: Long = 0x120L // bool; schema=m_bHasColorCorrection
        const val m_bHasFogScatteringParams: Long = 0x121L // bool; schema=m_bHasFogScatteringParams
        const val m_fogScatteringParams: Long = 0x124L // PostProcessingFogScatteringParameters_t; schema=m_fogScatteringParams
    }

    /** Read/write view of decodable fields declared directly by PostProcessingResource_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class PostProcessingResource_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_bHasTonemapParams: Boolean by bool(PostProcessingResource_t.m_bHasTonemapParams)
        /** Embedded reflected value: PostProcessingTonemapParameters_t. */
        val m_toneMapParams: Materialsystem2Schema.PostProcessingTonemapParameters_tStruct
            get() = Materialsystem2Schema.PostProcessingTonemapParameters_tStruct(base + PostProcessingResource_t.m_toneMapParams, mem)
        var m_bHasBloomParams: Boolean by bool(PostProcessingResource_t.m_bHasBloomParams)
        /** Embedded reflected value: PostProcessingBloomParameters_t. */
        val m_bloomParams: Materialsystem2Schema.PostProcessingBloomParameters_tStruct
            get() = Materialsystem2Schema.PostProcessingBloomParameters_tStruct(base + PostProcessingResource_t.m_bloomParams, mem)
        var m_bHasVignetteParams: Boolean by bool(PostProcessingResource_t.m_bHasVignetteParams)
        /** Embedded reflected value: PostProcessingVignetteParameters_t. */
        val m_vignetteParams: Materialsystem2Schema.PostProcessingVignetteParameters_tStruct
            get() = Materialsystem2Schema.PostProcessingVignetteParameters_tStruct(base + PostProcessingResource_t.m_vignetteParams, mem)
        var m_bHasLocalContrastParams: Boolean by bool(PostProcessingResource_t.m_bHasLocalContrastParams)
        /** Embedded reflected value: PostProcessingLocalContrastParameters_t. */
        val m_localConstrastParams: Materialsystem2Schema.PostProcessingLocalContrastParameters_tStruct
            get() = Materialsystem2Schema.PostProcessingLocalContrastParameters_tStruct(base + PostProcessingResource_t.m_localConstrastParams, mem)
        var m_nColorCorrectionVolumeDim: Int by int32(PostProcessingResource_t.m_nColorCorrectionVolumeDim)
        /** Raw address of m_colorCorrectionVolumeData: CUtlBinaryBlock; no safe value decoder was proven. */
        val m_colorCorrectionVolumeDataAddress: Long get() = base + PostProcessingResource_t.m_colorCorrectionVolumeData
        var m_bHasColorCorrection: Boolean by bool(PostProcessingResource_t.m_bHasColorCorrection)
        var m_bHasFogScatteringParams: Boolean by bool(PostProcessingResource_t.m_bHasFogScatteringParams)
        /** Embedded reflected value: PostProcessingFogScatteringParameters_t. */
        val m_fogScatteringParams: Materialsystem2Schema.PostProcessingFogScatteringParameters_tStruct
            get() = Materialsystem2Schema.PostProcessingFogScatteringParameters_tStruct(base + PostProcessingResource_t.m_fogScatteringParams, mem)
    }

    /** Fields declared directly by PostProcessingTonemapParameters_t. */
    object PostProcessingTonemapParameters_t {
        const val SCHEMA_NAME: String = "PostProcessingTonemapParameters_t"
        const val m_flExposureBias: Long = 0x0L // float32; schema=m_flExposureBias
        const val m_flShoulderStrength: Long = 0x4L // float32; schema=m_flShoulderStrength
        const val m_flLinearStrength: Long = 0x8L // float32; schema=m_flLinearStrength
        const val m_flLinearAngle: Long = 0xCL // float32; schema=m_flLinearAngle
        const val m_flToeStrength: Long = 0x10L // float32; schema=m_flToeStrength
        const val m_flToeNum: Long = 0x14L // float32; schema=m_flToeNum
        const val m_flToeDenom: Long = 0x18L // float32; schema=m_flToeDenom
        const val m_flWhitePoint: Long = 0x1CL // float32; schema=m_flWhitePoint
        const val m_flLuminanceSource: Long = 0x20L // float32; schema=m_flLuminanceSource
        const val m_flExposureBiasShadows: Long = 0x24L // float32; schema=m_flExposureBiasShadows
        const val m_flExposureBiasHighlights: Long = 0x28L // float32; schema=m_flExposureBiasHighlights
        const val m_flMinShadowLum: Long = 0x2CL // float32; schema=m_flMinShadowLum
        const val m_flMaxShadowLum: Long = 0x30L // float32; schema=m_flMaxShadowLum
        const val m_flMinHighlightLum: Long = 0x34L // float32; schema=m_flMinHighlightLum
        const val m_flMaxHighlightLum: Long = 0x38L // float32; schema=m_flMaxHighlightLum
    }

    /** Read/write view of decodable fields declared directly by PostProcessingTonemapParameters_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class PostProcessingTonemapParameters_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_flExposureBias: Float by float(PostProcessingTonemapParameters_t.m_flExposureBias)
        var m_flShoulderStrength: Float by float(PostProcessingTonemapParameters_t.m_flShoulderStrength)
        var m_flLinearStrength: Float by float(PostProcessingTonemapParameters_t.m_flLinearStrength)
        var m_flLinearAngle: Float by float(PostProcessingTonemapParameters_t.m_flLinearAngle)
        var m_flToeStrength: Float by float(PostProcessingTonemapParameters_t.m_flToeStrength)
        var m_flToeNum: Float by float(PostProcessingTonemapParameters_t.m_flToeNum)
        var m_flToeDenom: Float by float(PostProcessingTonemapParameters_t.m_flToeDenom)
        var m_flWhitePoint: Float by float(PostProcessingTonemapParameters_t.m_flWhitePoint)
        var m_flLuminanceSource: Float by float(PostProcessingTonemapParameters_t.m_flLuminanceSource)
        var m_flExposureBiasShadows: Float by float(PostProcessingTonemapParameters_t.m_flExposureBiasShadows)
        var m_flExposureBiasHighlights: Float by float(PostProcessingTonemapParameters_t.m_flExposureBiasHighlights)
        var m_flMinShadowLum: Float by float(PostProcessingTonemapParameters_t.m_flMinShadowLum)
        var m_flMaxShadowLum: Float by float(PostProcessingTonemapParameters_t.m_flMaxShadowLum)
        var m_flMinHighlightLum: Float by float(PostProcessingTonemapParameters_t.m_flMinHighlightLum)
        var m_flMaxHighlightLum: Float by float(PostProcessingTonemapParameters_t.m_flMaxHighlightLum)
    }

    /** Fields declared directly by PostProcessingVignetteParameters_t. */
    object PostProcessingVignetteParameters_t {
        const val SCHEMA_NAME: String = "PostProcessingVignetteParameters_t"
        const val m_flVignetteStrength: Long = 0x0L // float32; schema=m_flVignetteStrength
        const val m_vCenter: Long = 0x4L // Vector2D; schema=m_vCenter
        const val m_flRadius: Long = 0xCL // float32; schema=m_flRadius
        const val m_flRoundness: Long = 0x10L // float32; schema=m_flRoundness
        const val m_flFeather: Long = 0x14L // float32; schema=m_flFeather
        const val m_vColorTint: Long = 0x18L // Vector; schema=m_vColorTint
    }

    /** Read/write view of decodable fields declared directly by PostProcessingVignetteParameters_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class PostProcessingVignetteParameters_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_flVignetteStrength: Float by float(PostProcessingVignetteParameters_t.m_flVignetteStrength)
        /** Raw address of m_vCenter: Vector2D; no safe value decoder was proven. */
        val m_vCenterAddress: Long get() = base + PostProcessingVignetteParameters_t.m_vCenter
        var m_flRadius: Float by float(PostProcessingVignetteParameters_t.m_flRadius)
        var m_flRoundness: Float by float(PostProcessingVignetteParameters_t.m_flRoundness)
        var m_flFeather: Float by float(PostProcessingVignetteParameters_t.m_flFeather)
        /** Raw address of m_vColorTint: Vector; no safe value decoder was proven. */
        val m_vColorTintAddress: Long get() = base + PostProcessingVignetteParameters_t.m_vColorTint
    }

    object Enums {
        object VertJustification_e {
            const val SCHEMA_NAME: String = "VertJustification_e"
            const val VERT_JUSTIFICATION_BOTTOM: Long = 2L
            const val VERT_JUSTIFICATION_CENTER: Long = 1L
            const val VERT_JUSTIFICATION_NONE: Long = 3L
            const val VERT_JUSTIFICATION_TOP: Long = 0L
        }

    }
}
