// ============================================================
// networksystem.kt
// Auto-generated by source2offset; do not edit manually
// ============================================================

package org.kvxd.source2offset.offsets

import org.kvxd.unsafeKt.UnsafeKt
import org.kvxd.unsafeKt.mem.Struct

object NetworksystemSchema {

    /** Fields declared directly by ChangeAccessorFieldPathIndex_t. */
    object ChangeAccessorFieldPathIndex_t {
        const val SCHEMA_NAME: String = "ChangeAccessorFieldPathIndex_t"
        const val m_Value: Long = 0x0L // int32; schema=m_Value
    }

    class ChangeAccessorFieldPathIndex_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_Value: Int by int32(ChangeAccessorFieldPathIndex_t.m_Value)
    }

}
