// ============================================================
// offsets.kt
// Auto-generated by source2offset; do not edit manually
// ============================================================

package org.kvxd.source2offset.offsets

import org.kvxd.unsafeKt.UnsafeKt

/** Native-Linux private/global targets with confidence and provenance recorded in offsets.json.
 *  Constants preserve familiar dw* names where native semantics correspond; generated helpers enforce each access mode.
 *  Pointer-slot helpers dereference moduleBase + RVA; direct-address helpers do not. */
object Offsets {
    object Client {
        const val CGameEntitySystem_m_EntityClasses: Long = 0xAA0L
        fun CGameEntitySystem_m_EntityClassesAddress(objectAddress: Long): Long = objectAddress + CGameEntitySystem_m_EntityClasses

        const val CGameEntitySystem_m_EntityList: Long = 0x10L
        fun CGameEntitySystem_m_EntityListAddress(objectAddress: Long): Long = objectAddress + CGameEntitySystem_m_EntityList

        const val dwGameEntitySystem: Long = 0x465A6D0L
        fun dwGameEntitySystemSlotAddress(moduleBase: Long): Long = moduleBase + dwGameEntitySystem
        fun resolveDwGameEntitySystem(moduleBase: Long, mem: UnsafeKt): Long = mem.readLong(dwGameEntitySystemSlotAddress(moduleBase))

        const val dwGameRules: Long = 0x4679E50L
        fun dwGameRulesSlotAddress(moduleBase: Long): Long = moduleBase + dwGameRules
        fun resolveDwGameRules(moduleBase: Long, mem: UnsafeKt): Long = mem.readLong(dwGameRulesSlotAddress(moduleBase))

        const val dwGlobalVars: Long = 0x441E758L
        fun dwGlobalVarsSlotAddress(moduleBase: Long): Long = moduleBase + dwGlobalVars
        fun resolveDwGlobalVars(moduleBase: Long, mem: UnsafeKt): Long = mem.readLong(dwGlobalVarsSlotAddress(moduleBase))

        const val dwLocalPlayerController: Long = 0x464A7B8L
        fun dwLocalPlayerControllerSlotAddress(moduleBase: Long): Long = moduleBase + dwLocalPlayerController
        fun resolveDwLocalPlayerController(moduleBase: Long, mem: UnsafeKt): Long = mem.readLong(dwLocalPlayerControllerSlotAddress(moduleBase))

        const val dwPlantedC4s: Long = 0x4689560L
        fun dwPlantedC4sAddress(moduleBase: Long): Long = moduleBase + dwPlantedC4s

        const val dwViewMatrix: Long = 0x46822C0L
        fun dwViewMatrixAddress(moduleBase: Long): Long = moduleBase + dwViewMatrix

        const val dwViewRender: Long = 0x46823D0L
        fun dwViewRenderSlotAddress(moduleBase: Long): Long = moduleBase + dwViewRender
        fun resolveDwViewRender(moduleBase: Long, mem: UnsafeKt): Long = mem.readLong(dwViewRenderSlotAddress(moduleBase))

        const val dwViewToProjectionMatrix: Long = 0x4682300L
        fun dwViewToProjectionMatrixAddress(moduleBase: Long): Long = moduleBase + dwViewToProjectionMatrix

        const val dwWorldToProjectionMatrix: Long = 0x46822C0L
        fun dwWorldToProjectionMatrixAddress(moduleBase: Long): Long = moduleBase + dwWorldToProjectionMatrix

    }

}
