// ============================================================
// panorama.kt
// Auto-generated by source2offset; do not edit manually
// ============================================================

package org.kvxd.source2offset.offsets

import org.kvxd.unsafeKt.UnsafeKt
import org.kvxd.unsafeKt.mem.Struct

/**
 * Reflected schema data for libpanorama.so.
 *
 * Offset namespaces contain fields declared directly on each reflected class.
 * Struct wrappers deliberately do not inherit: the dump proves parent relationships,
 * but does not assume a universal native base-subobject displacement rule.
 * Fields with unknown value layout retain an Address accessor instead of an unsafe decoder.
 */
object PanoramaSchema {

    object Enums {
        object ELayoutNodeType {
            const val SCHEMA_NAME: String = "ELayoutNodeType"
            const val INCLUDE: Long = 5L
            const val PANEL: Long = 7L
            const val PANEL_ATTRIBUTE: Long = 8L
            const val PANEL_ATTRIBUTE_VALUE: Long = 9L
            const val REFERENCE_COMPILED: Long = 11L
            const val REFERENCE_CONTENT: Long = 10L
            const val REFERENCE_PASSTHROUGH: Long = 12L
            const val ROOT: Long = 0L
            const val SCRIPTS: Long = 3L
            const val SCRIPT_BODY: Long = 2L
            const val SNIPPET: Long = 6L
            const val SNIPPETS: Long = 4L
            const val STYLES: Long = 1L
        }

    }
}
