// ============================================================
// rendersystemvulkan.kt
// Auto-generated by source2offset; do not edit manually
// ============================================================

package org.kvxd.source2offset.offsets

import org.kvxd.unsafeKt.UnsafeKt
import org.kvxd.unsafeKt.mem.Struct

/**
 * Reflected schema data for librendersystemvulkan.so.
 *
 * Offset namespaces contain fields declared directly on each reflected class.
 * Struct wrappers deliberately do not inherit: the dump proves parent relationships,
 * but does not assume a universal native base-subobject displacement rule.
 * Fields with unknown value layout retain an Address accessor instead of an unsafe decoder.
 */
object RendersystemvulkanSchema {

    /** Fields declared directly by RenderInputLayoutField_t. */
    object RenderInputLayoutField_t {
        const val SCHEMA_NAME: String = "RenderInputLayoutField_t"
        const val m_pSemanticName: Long = 0x0L // char[32]; schema=m_pSemanticName
        const val m_nSemanticIndex: Long = 0x20L // int8; schema=m_nSemanticIndex
        const val m_nOffset: Long = 0x28L // int16; schema=m_nOffset
        const val m_nSlot: Long = 0x2AL // int8; schema=m_nSlot
        const val m_nSlotType: Long = 0x2BL // RenderSlotType_t; schema=m_nSlotType
        const val m_szShaderSemantic: Long = 0x2CL // char[32]; schema=m_szShaderSemantic
    }

    /** Read/write view of decodable fields declared directly by RenderInputLayoutField_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class RenderInputLayoutField_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_pSemanticName: char[32]; no safe value decoder was proven. */
        val m_pSemanticNameAddress: Long get() = base + RenderInputLayoutField_t.m_pSemanticName
        var m_nSemanticIndex: Byte by int8(RenderInputLayoutField_t.m_nSemanticIndex)
        var m_nOffset: Short by int16(RenderInputLayoutField_t.m_nOffset)
        var m_nSlot: Byte by int8(RenderInputLayoutField_t.m_nSlot)
        /** Raw address of m_nSlotType: RenderSlotType_t; no safe value decoder was proven. */
        val m_nSlotTypeAddress: Long get() = base + RenderInputLayoutField_t.m_nSlotType
        /** Raw address of m_szShaderSemantic: char[32]; no safe value decoder was proven. */
        val m_szShaderSemanticAddress: Long get() = base + RenderInputLayoutField_t.m_szShaderSemantic
    }

    /** Fields declared directly by RsBlendStateDesc_t. */
    object RsBlendStateDesc_t {
        const val SCHEMA_NAME: String = "RsBlendStateDesc_t"
        const val m_srcBlendBits: Long = 0x0L // uint32; schema=m_srcBlendBits
        const val m_blendOpBits: Long = 0x0L // bitfield:30; schema=m_blendOpBits
        const val m_bAlphaToCoverageEnable: Long = 0x0L // bitfield:1; schema=m_bAlphaToCoverageEnable
        const val m_bIndependentBlendEnable: Long = 0x0L // bitfield:1; schema=m_bIndependentBlendEnable
        const val m_destBlendBits: Long = 0x4L // uint32; schema=m_destBlendBits
        const val m_srcBlendAlphaBits: Long = 0x8L // uint32; schema=m_srcBlendAlphaBits
        const val m_destBlendAlphaBits: Long = 0xCL // uint32; schema=m_destBlendAlphaBits
        const val m_renderTargetWriteMaskBits: Long = 0x10L // uint32; schema=m_renderTargetWriteMaskBits
        const val m_blendOpAlphaBits: Long = 0x18L // uint32; schema=m_blendOpAlphaBits
        const val m_blendEnableBits: Long = 0x1CL // uint8; schema=m_blendEnableBits
        const val m_srgbWriteEnableBits: Long = 0x1DL // uint8; schema=m_srgbWriteEnableBits
    }

    /** Read/write view of decodable fields declared directly by RsBlendStateDesc_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class RsBlendStateDesc_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_srcBlendBits: UInt by uint32(RsBlendStateDesc_t.m_srcBlendBits)
        /** Raw address of m_blendOpBits: bitfield:30; no safe value decoder was proven. */
        val m_blendOpBitsAddress: Long get() = base + RsBlendStateDesc_t.m_blendOpBits
        /** Raw address of m_bAlphaToCoverageEnable: bitfield:1; no safe value decoder was proven. */
        val m_bAlphaToCoverageEnableAddress: Long get() = base + RsBlendStateDesc_t.m_bAlphaToCoverageEnable
        /** Raw address of m_bIndependentBlendEnable: bitfield:1; no safe value decoder was proven. */
        val m_bIndependentBlendEnableAddress: Long get() = base + RsBlendStateDesc_t.m_bIndependentBlendEnable
        var m_destBlendBits: UInt by uint32(RsBlendStateDesc_t.m_destBlendBits)
        var m_srcBlendAlphaBits: UInt by uint32(RsBlendStateDesc_t.m_srcBlendAlphaBits)
        var m_destBlendAlphaBits: UInt by uint32(RsBlendStateDesc_t.m_destBlendAlphaBits)
        var m_renderTargetWriteMaskBits: UInt by uint32(RsBlendStateDesc_t.m_renderTargetWriteMaskBits)
        var m_blendOpAlphaBits: UInt by uint32(RsBlendStateDesc_t.m_blendOpAlphaBits)
        var m_blendEnableBits: UByte by uint8(RsBlendStateDesc_t.m_blendEnableBits)
        var m_srgbWriteEnableBits: UByte by uint8(RsBlendStateDesc_t.m_srgbWriteEnableBits)
    }

    /** Fields declared directly by RsDepthStencilStateDesc_t. */
    object RsDepthStencilStateDesc_t {
        const val SCHEMA_NAME: String = "RsDepthStencilStateDesc_t"
        const val m_bDepthTestEnable: Long = 0x0L // bitfield:1; schema=m_bDepthTestEnable
        const val m_bDepthWriteEnable: Long = 0x0L // bitfield:1; schema=m_bDepthWriteEnable
        const val m_depthFunc: Long = 0x1L // RsComparison_t; schema=m_depthFunc
        const val m_stencilState: Long = 0x2L // RsStencilStateDesc_t; schema=m_stencilState
    }

    /** Read/write view of decodable fields declared directly by RsDepthStencilStateDesc_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class RsDepthStencilStateDesc_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_bDepthTestEnable: bitfield:1; no safe value decoder was proven. */
        val m_bDepthTestEnableAddress: Long get() = base + RsDepthStencilStateDesc_t.m_bDepthTestEnable
        /** Raw address of m_bDepthWriteEnable: bitfield:1; no safe value decoder was proven. */
        val m_bDepthWriteEnableAddress: Long get() = base + RsDepthStencilStateDesc_t.m_bDepthWriteEnable
        /** Raw address of m_depthFunc: RsComparison_t; no safe value decoder was proven. */
        val m_depthFuncAddress: Long get() = base + RsDepthStencilStateDesc_t.m_depthFunc
        /** Embedded reflected value: RsStencilStateDesc_t. */
        val m_stencilState: RendersystemvulkanSchema.RsStencilStateDesc_tStruct
            get() = RendersystemvulkanSchema.RsStencilStateDesc_tStruct(base + RsDepthStencilStateDesc_t.m_stencilState, mem)
    }

    /** Fields declared directly by RsRasterizerStateDesc_t. */
    object RsRasterizerStateDesc_t {
        const val SCHEMA_NAME: String = "RsRasterizerStateDesc_t"
        const val m_nFillMode: Long = 0x0L // RsFillMode_t; schema=m_nFillMode
        const val m_nCullMode: Long = 0x1L // RsCullMode_t; schema=m_nCullMode
        const val m_bDepthClipEnable: Long = 0x2L // bool; schema=m_bDepthClipEnable
        const val m_bMultisampleEnable: Long = 0x3L // bool; schema=m_bMultisampleEnable
        const val m_nDepthBias: Long = 0x4L // int32; schema=m_nDepthBias
        const val m_flDepthBiasClamp: Long = 0x8L // float32; schema=m_flDepthBiasClamp
        const val m_flSlopeScaledDepthBias: Long = 0xCL // float32; schema=m_flSlopeScaledDepthBias
    }

    /** Read/write view of decodable fields declared directly by RsRasterizerStateDesc_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class RsRasterizerStateDesc_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_nFillMode: RsFillMode_t; no safe value decoder was proven. */
        val m_nFillModeAddress: Long get() = base + RsRasterizerStateDesc_t.m_nFillMode
        /** Raw address of m_nCullMode: RsCullMode_t; no safe value decoder was proven. */
        val m_nCullModeAddress: Long get() = base + RsRasterizerStateDesc_t.m_nCullMode
        var m_bDepthClipEnable: Boolean by bool(RsRasterizerStateDesc_t.m_bDepthClipEnable)
        var m_bMultisampleEnable: Boolean by bool(RsRasterizerStateDesc_t.m_bMultisampleEnable)
        var m_nDepthBias: Int by int32(RsRasterizerStateDesc_t.m_nDepthBias)
        var m_flDepthBiasClamp: Float by float(RsRasterizerStateDesc_t.m_flDepthBiasClamp)
        var m_flSlopeScaledDepthBias: Float by float(RsRasterizerStateDesc_t.m_flSlopeScaledDepthBias)
    }

    /** Fields declared directly by RsStencilStateDesc_t. */
    object RsStencilStateDesc_t {
        const val SCHEMA_NAME: String = "RsStencilStateDesc_t"
        const val m_bStencilEnable: Long = 0x0L // bitfield:1; schema=m_bStencilEnable
        const val m_frontStencilFailOp: Long = 0x0L // bitfield:3; schema=m_frontStencilFailOp
        const val m_frontStencilDepthFailOp: Long = 0x0L // bitfield:3; schema=m_frontStencilDepthFailOp
        const val m_frontStencilPassOp: Long = 0x0L // bitfield:3; schema=m_frontStencilPassOp
        const val m_frontStencilFunc: Long = 0x0L // bitfield:3; schema=m_frontStencilFunc
        const val m_backStencilFailOp: Long = 0x0L // bitfield:3; schema=m_backStencilFailOp
        const val m_backStencilDepthFailOp: Long = 0x0L // bitfield:3; schema=m_backStencilDepthFailOp
        const val m_backStencilPassOp: Long = 0x0L // bitfield:3; schema=m_backStencilPassOp
        const val m_backStencilFunc: Long = 0x0L // bitfield:3; schema=m_backStencilFunc
        const val m_nStencilReadMask: Long = 0x4L // uint8; schema=m_nStencilReadMask
        const val m_nStencilWriteMask: Long = 0x5L // uint8; schema=m_nStencilWriteMask
    }

    /** Read/write view of decodable fields declared directly by RsStencilStateDesc_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class RsStencilStateDesc_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_bStencilEnable: bitfield:1; no safe value decoder was proven. */
        val m_bStencilEnableAddress: Long get() = base + RsStencilStateDesc_t.m_bStencilEnable
        /** Raw address of m_frontStencilFailOp: bitfield:3; no safe value decoder was proven. */
        val m_frontStencilFailOpAddress: Long get() = base + RsStencilStateDesc_t.m_frontStencilFailOp
        /** Raw address of m_frontStencilDepthFailOp: bitfield:3; no safe value decoder was proven. */
        val m_frontStencilDepthFailOpAddress: Long get() = base + RsStencilStateDesc_t.m_frontStencilDepthFailOp
        /** Raw address of m_frontStencilPassOp: bitfield:3; no safe value decoder was proven. */
        val m_frontStencilPassOpAddress: Long get() = base + RsStencilStateDesc_t.m_frontStencilPassOp
        /** Raw address of m_frontStencilFunc: bitfield:3; no safe value decoder was proven. */
        val m_frontStencilFuncAddress: Long get() = base + RsStencilStateDesc_t.m_frontStencilFunc
        /** Raw address of m_backStencilFailOp: bitfield:3; no safe value decoder was proven. */
        val m_backStencilFailOpAddress: Long get() = base + RsStencilStateDesc_t.m_backStencilFailOp
        /** Raw address of m_backStencilDepthFailOp: bitfield:3; no safe value decoder was proven. */
        val m_backStencilDepthFailOpAddress: Long get() = base + RsStencilStateDesc_t.m_backStencilDepthFailOp
        /** Raw address of m_backStencilPassOp: bitfield:3; no safe value decoder was proven. */
        val m_backStencilPassOpAddress: Long get() = base + RsStencilStateDesc_t.m_backStencilPassOp
        /** Raw address of m_backStencilFunc: bitfield:3; no safe value decoder was proven. */
        val m_backStencilFuncAddress: Long get() = base + RsStencilStateDesc_t.m_backStencilFunc
        var m_nStencilReadMask: UByte by uint8(RsStencilStateDesc_t.m_nStencilReadMask)
        var m_nStencilWriteMask: UByte by uint8(RsStencilStateDesc_t.m_nStencilWriteMask)
    }

    /** Fields declared directly by SheetSequenceIntegerId_t. */
    object SheetSequenceIntegerId_t {
        const val SCHEMA_NAME: String = "SheetSequenceIntegerId_t"
        const val m_Value: Long = 0x0L // uint32; schema=m_Value
    }

    /** Read/write view of decodable fields declared directly by SheetSequenceIntegerId_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class SheetSequenceIntegerId_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_Value: UInt by uint32(SheetSequenceIntegerId_t.m_Value)
    }

    /** Fields declared directly by VsInputSignatureElement_t. */
    object VsInputSignatureElement_t {
        const val SCHEMA_NAME: String = "VsInputSignatureElement_t"
        const val m_pName: Long = 0x0L // char[64]; schema=m_pName
        const val m_pSemantic: Long = 0x40L // char[64]; schema=m_pSemantic
        const val m_pD3DSemanticName: Long = 0x80L // char[64]; schema=m_pD3DSemanticName
        const val m_nD3DSemanticIndex: Long = 0xC0L // int32; schema=m_nD3DSemanticIndex
    }

    /** Read/write view of decodable fields declared directly by VsInputSignatureElement_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class VsInputSignatureElement_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_pName: char[64]; no safe value decoder was proven. */
        val m_pNameAddress: Long get() = base + VsInputSignatureElement_t.m_pName
        /** Raw address of m_pSemantic: char[64]; no safe value decoder was proven. */
        val m_pSemanticAddress: Long get() = base + VsInputSignatureElement_t.m_pSemantic
        /** Raw address of m_pD3DSemanticName: char[64]; no safe value decoder was proven. */
        val m_pD3DSemanticNameAddress: Long get() = base + VsInputSignatureElement_t.m_pD3DSemanticName
        var m_nD3DSemanticIndex: Int by int32(VsInputSignatureElement_t.m_nD3DSemanticIndex)
    }

    /** Fields declared directly by VsInputSignature_t. */
    object VsInputSignature_t {
        const val SCHEMA_NAME: String = "VsInputSignature_t"
        const val m_elems: Long = 0x0L // CUtlVector<VsInputSignatureElement_t>; schema=m_elems
        const val m_depth_elems: Long = 0x18L // CUtlVector<VsInputSignatureElement_t>; schema=m_depth_elems
    }

    /** Read/write view of decodable fields declared directly by VsInputSignature_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class VsInputSignature_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_elems: CUtlVector<VsInputSignatureElement_t>; no safe value decoder was proven. */
        val m_elemsAddress: Long get() = base + VsInputSignature_t.m_elems
        /** Raw address of m_depth_elems: CUtlVector<VsInputSignatureElement_t>; no safe value decoder was proven. */
        val m_depth_elemsAddress: Long get() = base + VsInputSignature_t.m_depth_elems
    }

    object Enums {
        object RenderPrimitiveType_t {
            const val SCHEMA_NAME: String = "RenderPrimitiveType_t"
            const val RENDER_PRIM_COMPUTE_SHADER: Long = 11L
            const val RENDER_PRIM_HETEROGENOUS: Long = 10L
            const val RENDER_PRIM_INSTANCED_QUADS: Long = 9L
            const val RENDER_PRIM_LINES: Long = 1L
            const val RENDER_PRIM_LINES_WITH_ADJACENCY: Long = 2L
            const val RENDER_PRIM_LINE_STRIP: Long = 3L
            const val RENDER_PRIM_LINE_STRIP_WITH_ADJACENCY: Long = 4L
            const val RENDER_PRIM_MESH_SHADER: Long = 12L
            const val RENDER_PRIM_POINTS: Long = 0L
            const val RENDER_PRIM_TRIANGLES: Long = 5L
            const val RENDER_PRIM_TRIANGLES_WITH_ADJACENCY: Long = 6L
            const val RENDER_PRIM_TRIANGLE_STRIP: Long = 7L
            const val RENDER_PRIM_TRIANGLE_STRIP_WITH_ADJACENCY: Long = 8L
            const val RENDER_PRIM_TYPE_COUNT: Long = 13L
        }

    }
}
