// ============================================================
// resourcesystem.kt
// Auto-generated by source2offset; do not edit manually
// ============================================================

package org.kvxd.source2offset.offsets

import org.kvxd.unsafeKt.UnsafeKt
import org.kvxd.unsafeKt.mem.Struct

/**
 * Reflected schema data for libresourcesystem.so.
 *
 * Offset namespaces contain fields declared directly on each reflected class.
 * Struct wrappers deliberately do not inherit: the dump proves parent relationships,
 * but does not assume a universal native base-subobject displacement rule.
 * Fields with unknown value layout retain an Address accessor instead of an unsafe decoder.
 */
object ResourcesystemSchema {

    /** Fields declared directly by AABB_t. */
    object AABB_t {
        const val SCHEMA_NAME: String = "AABB_t"
        const val m_vMinBounds: Long = 0x0L // Vector; schema=m_vMinBounds
        const val m_vMaxBounds: Long = 0xCL // Vector; schema=m_vMaxBounds
    }

    /** Read/write view of decodable fields declared directly by AABB_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class AABB_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_vMinBounds: Vector; no safe value decoder was proven. */
        val m_vMinBoundsAddress: Long get() = base + AABB_t.m_vMinBounds
        /** Raw address of m_vMaxBounds: Vector; no safe value decoder was proven. */
        val m_vMaxBoundsAddress: Long get() = base + AABB_t.m_vMaxBounds
    }

    /** Fields declared directly by CFuseProgram. */
    object CFuseProgram {
        const val SCHEMA_NAME: String = "CFuseProgram"
        const val m_programBuffer: Long = 0x0L // CUtlVector<uint8>; schema=m_programBuffer
        const val m_variablesRead: Long = 0x18L // CUtlVector<FuseVariableIndex_t>; schema=m_variablesRead
        const val m_variablesWritten: Long = 0x30L // CUtlVector<FuseVariableIndex_t>; schema=m_variablesWritten
        const val m_nMaxTempVarsUsed: Long = 0x48L // int32; schema=m_nMaxTempVarsUsed
    }

    /** Read/write view of decodable fields declared directly by CFuseProgram.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CFuseProgramStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_programBuffer: CUtlVector<uint8>; no safe value decoder was proven. */
        val m_programBufferAddress: Long get() = base + CFuseProgram.m_programBuffer
        /** Raw address of m_variablesRead: CUtlVector<FuseVariableIndex_t>; no safe value decoder was proven. */
        val m_variablesReadAddress: Long get() = base + CFuseProgram.m_variablesRead
        /** Raw address of m_variablesWritten: CUtlVector<FuseVariableIndex_t>; no safe value decoder was proven. */
        val m_variablesWrittenAddress: Long get() = base + CFuseProgram.m_variablesWritten
        var m_nMaxTempVarsUsed: Int by int32(CFuseProgram.m_nMaxTempVarsUsed)
    }

    /** Fields declared directly by CFuseSymbolTable. */
    object CFuseSymbolTable {
        const val SCHEMA_NAME: String = "CFuseSymbolTable"
        const val m_constants: Long = 0x0L // CUtlVector<ConstantInfo_t>; schema=m_constants
        const val m_variables: Long = 0x18L // CUtlVector<VariableInfo_t>; schema=m_variables
        const val m_functions: Long = 0x30L // CUtlVector<FunctionInfo_t>; schema=m_functions
        const val m_constantMap: Long = 0x48L // CUtlHashtable<CUtlStringToken,int32>; schema=m_constantMap
        const val m_variableMap: Long = 0x68L // CUtlHashtable<CUtlStringToken,int32>; schema=m_variableMap
        const val m_functionMap: Long = 0x88L // CUtlHashtable<CUtlStringToken,int32>; schema=m_functionMap
    }

    /** Read/write view of decodable fields declared directly by CFuseSymbolTable.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CFuseSymbolTableStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_constants: CUtlVector<ConstantInfo_t>; no safe value decoder was proven. */
        val m_constantsAddress: Long get() = base + CFuseSymbolTable.m_constants
        /** Raw address of m_variables: CUtlVector<VariableInfo_t>; no safe value decoder was proven. */
        val m_variablesAddress: Long get() = base + CFuseSymbolTable.m_variables
        /** Raw address of m_functions: CUtlVector<FunctionInfo_t>; no safe value decoder was proven. */
        val m_functionsAddress: Long get() = base + CFuseSymbolTable.m_functions
        /** Raw address of m_constantMap: CUtlHashtable<CUtlStringToken,int32>; no safe value decoder was proven. */
        val m_constantMapAddress: Long get() = base + CFuseSymbolTable.m_constantMap
        /** Raw address of m_variableMap: CUtlHashtable<CUtlStringToken,int32>; no safe value decoder was proven. */
        val m_variableMapAddress: Long get() = base + CFuseSymbolTable.m_variableMap
        /** Raw address of m_functionMap: CUtlHashtable<CUtlStringToken,int32>; no safe value decoder was proven. */
        val m_functionMapAddress: Long get() = base + CFuseSymbolTable.m_functionMap
    }

    /** Fields declared directly by ConstantInfo_t. */
    object ConstantInfo_t {
        const val SCHEMA_NAME: String = "ConstantInfo_t"
        const val m_name: Long = 0x0L // CUtlString; schema=m_name
        const val m_nameToken: Long = 0x8L // CUtlStringToken; schema=m_nameToken
        const val m_flValue: Long = 0xCL // float32; schema=m_flValue
    }

    /** Read/write view of decodable fields declared directly by ConstantInfo_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class ConstantInfo_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_name: Long by ptr64(ConstantInfo_t.m_name)
        /** Raw address of m_nameToken: CUtlStringToken; no safe value decoder was proven. */
        val m_nameTokenAddress: Long get() = base + ConstantInfo_t.m_nameToken
        var m_flValue: Float by float(ConstantInfo_t.m_flValue)
    }

    /** Fields declared directly by FourQuaternions. */
    object FourQuaternions {
        const val SCHEMA_NAME: String = "FourQuaternions"
        const val x: Long = 0x0L // fltx4; schema=x
        const val y: Long = 0x10L // fltx4; schema=y
        const val z: Long = 0x20L // fltx4; schema=z
        const val w: Long = 0x30L // fltx4; schema=w
    }

    /** Read/write view of decodable fields declared directly by FourQuaternions.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class FourQuaternionsStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of x: fltx4; no safe value decoder was proven. */
        val xAddress: Long get() = base + FourQuaternions.x
        /** Raw address of y: fltx4; no safe value decoder was proven. */
        val yAddress: Long get() = base + FourQuaternions.y
        /** Raw address of z: fltx4; no safe value decoder was proven. */
        val zAddress: Long get() = base + FourQuaternions.z
        /** Raw address of w: fltx4; no safe value decoder was proven. */
        val wAddress: Long get() = base + FourQuaternions.w
    }

    /** Fields declared directly by FunctionInfo_t. */
    object FunctionInfo_t {
        const val SCHEMA_NAME: String = "FunctionInfo_t"
        const val m_name: Long = 0x8L // CUtlString; schema=m_name
        const val m_nameToken: Long = 0x10L // CUtlStringToken; schema=m_nameToken
        const val m_nParamCount: Long = 0x14L // int32; schema=m_nParamCount
        const val m_nIndex: Long = 0x18L // FuseFunctionIndex_t; schema=m_nIndex
        const val m_bIsPure: Long = 0x1AL // bool; schema=m_bIsPure
    }

    /** Read/write view of decodable fields declared directly by FunctionInfo_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class FunctionInfo_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_name: Long by ptr64(FunctionInfo_t.m_name)
        /** Raw address of m_nameToken: CUtlStringToken; no safe value decoder was proven. */
        val m_nameTokenAddress: Long get() = base + FunctionInfo_t.m_nameToken
        var m_nParamCount: Int by int32(FunctionInfo_t.m_nParamCount)
        /** Embedded reflected value: FuseFunctionIndex_t. */
        val m_nIndex: ResourcesystemSchema.FuseFunctionIndex_tStruct
            get() = ResourcesystemSchema.FuseFunctionIndex_tStruct(base + FunctionInfo_t.m_nIndex, mem)
        var m_bIsPure: Boolean by bool(FunctionInfo_t.m_bIsPure)
    }

    /** Fields declared directly by FuseFunctionIndex_t. */
    object FuseFunctionIndex_t {
        const val SCHEMA_NAME: String = "FuseFunctionIndex_t"
        const val m_Value: Long = 0x0L // uint16; schema=m_Value
    }

    /** Read/write view of decodable fields declared directly by FuseFunctionIndex_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class FuseFunctionIndex_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_Value: UShort by uint16(FuseFunctionIndex_t.m_Value)
    }

    /** Fields declared directly by FuseVariableIndex_t. */
    object FuseVariableIndex_t {
        const val SCHEMA_NAME: String = "FuseVariableIndex_t"
        const val m_Value: Long = 0x0L // uint16; schema=m_Value
    }

    /** Read/write view of decodable fields declared directly by FuseVariableIndex_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class FuseVariableIndex_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_Value: UShort by uint16(FuseVariableIndex_t.m_Value)
    }

    /** Fields declared directly by InfoForResourceTypeCAnimData. */
    object InfoForResourceTypeCAnimData {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCAnimData"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCAnimData.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCAnimDataStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCAnimationGroup. */
    object InfoForResourceTypeCAnimationGroup {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCAnimationGroup"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCAnimationGroup.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCAnimationGroupStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCCSGOEconItem. */
    object InfoForResourceTypeCCSGOEconItem {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCCSGOEconItem"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCCSGOEconItem.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCCSGOEconItemStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCChoreoSceneResource. */
    object InfoForResourceTypeCChoreoSceneResource {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCChoreoSceneResource"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCChoreoSceneResource.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCChoreoSceneResourceStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCCompositeMaterialKit. */
    object InfoForResourceTypeCCompositeMaterialKit {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCCompositeMaterialKit"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCCompositeMaterialKit.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCCompositeMaterialKitStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCDOTANovelsList. */
    object InfoForResourceTypeCDOTANovelsList {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCDOTANovelsList"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCDOTANovelsList.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCDOTANovelsListStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCDOTAPatchNotesList. */
    object InfoForResourceTypeCDOTAPatchNotesList {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCDOTAPatchNotesList"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCDOTAPatchNotesList.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCDOTAPatchNotesListStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCDotaItemDefinitionResource. */
    object InfoForResourceTypeCDotaItemDefinitionResource {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCDotaItemDefinitionResource"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCDotaItemDefinitionResource.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCDotaItemDefinitionResourceStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCEntityLump. */
    object InfoForResourceTypeCEntityLump {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCEntityLump"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCEntityLump.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCEntityLumpStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCGcExportableExternalData. */
    object InfoForResourceTypeCGcExportableExternalData {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCGcExportableExternalData"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCGcExportableExternalData.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCGcExportableExternalDataStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCJavaScriptResource. */
    object InfoForResourceTypeCJavaScriptResource {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCJavaScriptResource"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCJavaScriptResource.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCJavaScriptResourceStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCModel. */
    object InfoForResourceTypeCModel {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCModel"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCModel.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCModelStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCMorphSetData. */
    object InfoForResourceTypeCMorphSetData {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCMorphSetData"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCMorphSetData.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCMorphSetDataStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCNmClip. */
    object InfoForResourceTypeCNmClip {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCNmClip"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCNmClip.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCNmClipStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCNmGraphDefinition. */
    object InfoForResourceTypeCNmGraphDefinition {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCNmGraphDefinition"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCNmGraphDefinition.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCNmGraphDefinitionStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCNmSkeleton. */
    object InfoForResourceTypeCNmSkeleton {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCNmSkeleton"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCNmSkeleton.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCNmSkeletonStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCPanoramaDynamicImages. */
    object InfoForResourceTypeCPanoramaDynamicImages {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCPanoramaDynamicImages"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCPanoramaDynamicImages.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCPanoramaDynamicImagesStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCPanoramaLayout. */
    object InfoForResourceTypeCPanoramaLayout {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCPanoramaLayout"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCPanoramaLayout.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCPanoramaLayoutStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCPanoramaStyle. */
    object InfoForResourceTypeCPanoramaStyle {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCPanoramaStyle"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCPanoramaStyle.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCPanoramaStyleStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCPhysAggregateData. */
    object InfoForResourceTypeCPhysAggregateData {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCPhysAggregateData"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCPhysAggregateData.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCPhysAggregateDataStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCPostProcessingResource. */
    object InfoForResourceTypeCPostProcessingResource {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCPostProcessingResource"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCPostProcessingResource.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCPostProcessingResourceStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCRenderMesh. */
    object InfoForResourceTypeCRenderMesh {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCRenderMesh"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCRenderMesh.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCRenderMeshStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCResponseRulesList. */
    object InfoForResourceTypeCResponseRulesList {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCResponseRulesList"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCResponseRulesList.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCResponseRulesListStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCSequenceGroupData. */
    object InfoForResourceTypeCSequenceGroupData {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCSequenceGroupData"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCSequenceGroupData.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCSequenceGroupDataStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCSmartProp. */
    object InfoForResourceTypeCSmartProp {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCSmartProp"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCSmartProp.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCSmartPropStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCSurfaceGraph. */
    object InfoForResourceTypeCSurfaceGraph {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCSurfaceGraph"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCSurfaceGraph.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCSurfaceGraphStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCTestResourceData. */
    object InfoForResourceTypeCTestResourceData {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCTestResourceData"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCTestResourceData.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCTestResourceDataStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCTextureBase. */
    object InfoForResourceTypeCTextureBase {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCTextureBase"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCTextureBase.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCTextureBaseStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCTypeScriptResource. */
    object InfoForResourceTypeCTypeScriptResource {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCTypeScriptResource"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCTypeScriptResource.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCTypeScriptResourceStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCVDataItemDefs. */
    object InfoForResourceTypeCVDataItemDefs {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCVDataItemDefs"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCVDataItemDefs.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCVDataItemDefsStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCVDataResource. */
    object InfoForResourceTypeCVDataResource {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCVDataResource"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCVDataResource.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCVDataResourceStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCVMixListResource. */
    object InfoForResourceTypeCVMixListResource {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCVMixListResource"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCVMixListResource.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCVMixListResourceStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCVPhysXSurfacePropertiesList. */
    object InfoForResourceTypeCVPhysXSurfacePropertiesList {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCVPhysXSurfacePropertiesList"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCVPhysXSurfacePropertiesList.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCVPhysXSurfacePropertiesListStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCVSoundEventScriptList. */
    object InfoForResourceTypeCVSoundEventScriptList {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCVSoundEventScriptList"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCVSoundEventScriptList.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCVSoundEventScriptListStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCVSoundStackScriptList. */
    object InfoForResourceTypeCVSoundStackScriptList {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCVSoundStackScriptList"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCVSoundStackScriptList.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCVSoundStackScriptListStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCVoiceContainerBase. */
    object InfoForResourceTypeCVoiceContainerBase {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCVoiceContainerBase"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCVoiceContainerBase.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCVoiceContainerBaseStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCVoxelVisibility. */
    object InfoForResourceTypeCVoxelVisibility {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCVoxelVisibility"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCVoxelVisibility.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCVoxelVisibilityStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeCWorldNode. */
    object InfoForResourceTypeCWorldNode {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCWorldNode"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeCWorldNode.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeCWorldNodeStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeIAnimGraphModelBinding. */
    object InfoForResourceTypeIAnimGraphModelBinding {
        const val SCHEMA_NAME: String = "InfoForResourceTypeIAnimGraphModelBinding"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeIAnimGraphModelBinding.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeIAnimGraphModelBindingStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeIMaterial2. */
    object InfoForResourceTypeIMaterial2 {
        const val SCHEMA_NAME: String = "InfoForResourceTypeIMaterial2"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeIMaterial2.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeIMaterial2Struct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeIParticleSnapshot. */
    object InfoForResourceTypeIParticleSnapshot {
        const val SCHEMA_NAME: String = "InfoForResourceTypeIParticleSnapshot"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeIParticleSnapshot.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeIParticleSnapshotStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeIParticleSystemDefinition. */
    object InfoForResourceTypeIParticleSystemDefinition {
        const val SCHEMA_NAME: String = "InfoForResourceTypeIParticleSystemDefinition"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeIParticleSystemDefinition.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeIParticleSystemDefinitionStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeIPulseGraphDef. */
    object InfoForResourceTypeIPulseGraphDef {
        const val SCHEMA_NAME: String = "InfoForResourceTypeIPulseGraphDef"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeIPulseGraphDef.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeIPulseGraphDefStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeIVectorGraphic. */
    object InfoForResourceTypeIVectorGraphic {
        const val SCHEMA_NAME: String = "InfoForResourceTypeIVectorGraphic"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeIVectorGraphic.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeIVectorGraphicStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeManifestTestResource_t. */
    object InfoForResourceTypeManifestTestResource_t {
        const val SCHEMA_NAME: String = "InfoForResourceTypeManifestTestResource_t"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeManifestTestResource_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeManifestTestResource_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeProceduralTestResource_t. */
    object InfoForResourceTypeProceduralTestResource_t {
        const val SCHEMA_NAME: String = "InfoForResourceTypeProceduralTestResource_t"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeProceduralTestResource_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeProceduralTestResource_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by InfoForResourceTypeWorld_t. */
    object InfoForResourceTypeWorld_t {
        const val SCHEMA_NAME: String = "InfoForResourceTypeWorld_t"
    }

    /** Read/write view of decodable fields declared directly by InfoForResourceTypeWorld_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class InfoForResourceTypeWorld_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by ManifestTestResource_t. */
    object ManifestTestResource_t {
        const val SCHEMA_NAME: String = "ManifestTestResource_t"
        const val m_name: Long = 0x0L // CUtlString; schema=m_name
        const val m_child: Long = 0x8L // CStrongHandle<InfoForResourceTypeManifestTestResource_t>; schema=m_child
    }

    /** Read/write view of decodable fields declared directly by ManifestTestResource_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class ManifestTestResource_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_name: Long by ptr64(ManifestTestResource_t.m_name)
        /** Raw address of m_child: CStrongHandle<InfoForResourceTypeManifestTestResource_t>; no safe value decoder was proven. */
        val m_childAddress: Long get() = base + ManifestTestResource_t.m_child
    }

    /** Fields declared directly by PackedAABB_t. */
    object PackedAABB_t {
        const val SCHEMA_NAME: String = "PackedAABB_t"
        const val m_nPackedMin: Long = 0x0L // uint32; schema=m_nPackedMin
        const val m_nPackedMax: Long = 0x4L // uint32; schema=m_nPackedMax
    }

    /** Read/write view of decodable fields declared directly by PackedAABB_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class PackedAABB_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_nPackedMin: UInt by uint32(PackedAABB_t.m_nPackedMin)
        var m_nPackedMax: UInt by uint32(PackedAABB_t.m_nPackedMax)
    }

    /** Fields declared directly by VariableInfo_t. */
    object VariableInfo_t {
        const val SCHEMA_NAME: String = "VariableInfo_t"
        const val m_name: Long = 0x0L // CUtlString; schema=m_name
        const val m_nameToken: Long = 0x8L // CUtlStringToken; schema=m_nameToken
        const val m_nIndex: Long = 0xCL // FuseVariableIndex_t; schema=m_nIndex
        const val m_nNumComponents: Long = 0xEL // uint8; schema=m_nNumComponents
        const val m_eVarType: Long = 0xFL // FuseVariableType_t; schema=m_eVarType
        const val m_eAccess: Long = 0x10L // FuseVariableAccess_t; schema=m_eAccess
    }

    /** Read/write view of decodable fields declared directly by VariableInfo_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class VariableInfo_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_name: Long by ptr64(VariableInfo_t.m_name)
        /** Raw address of m_nameToken: CUtlStringToken; no safe value decoder was proven. */
        val m_nameTokenAddress: Long get() = base + VariableInfo_t.m_nameToken
        /** Embedded reflected value: FuseVariableIndex_t. */
        val m_nIndex: ResourcesystemSchema.FuseVariableIndex_tStruct
            get() = ResourcesystemSchema.FuseVariableIndex_tStruct(base + VariableInfo_t.m_nIndex, mem)
        var m_nNumComponents: UByte by uint8(VariableInfo_t.m_nNumComponents)
        /** Raw address of m_eVarType: FuseVariableType_t; no safe value decoder was proven. */
        val m_eVarTypeAddress: Long get() = base + VariableInfo_t.m_eVarType
        /** Raw address of m_eAccess: FuseVariableAccess_t; no safe value decoder was proven. */
        val m_eAccessAddress: Long get() = base + VariableInfo_t.m_eAccess
    }

    object Enums {
        object FuseVariableType_t {
            const val SCHEMA_NAME: String = "FuseVariableType_t"
            const val BOOL: Long = 1L
            const val FLOAT32: Long = 8L
            const val INT16: Long = 3L
            const val INT32: Long = 4L
            const val INT8: Long = 2L
            const val INVALID: Long = 0L
            const val UINT16: Long = 6L
            const val UINT32: Long = 7L
            const val UINT8: Long = 5L
        }

    }
}
