// ============================================================
// runtime_roots.kt
// Auto-generated by source2offset; do not edit manually
// ============================================================

package org.kvxd.source2offset.offsets

import org.kvxd.unsafeKt.UnsafeKt

object RuntimeRoots {
    object GameEntitySystem {
        const val SOURCE_MODULE: String = "libengine2.so"
        const val SOURCE_INTERFACE: String = "GameResourceServiceClientV001"
        const val SOURCE_INTERFACE_RVA: Long = 0x9C3B20L
        const val MEMBER_OFFSET: Long = 0x50L
        const val VERIFIED_TARGET_TYPE: String = "CGameEntitySystem"

        /** Resolve the live target through the RTTI-verified interface relationship. */
        fun resolve(sourceModuleBase: Long, mem: UnsafeKt): Long =
            mem.readLong(sourceModuleBase + SOURCE_INTERFACE_RVA + MEMBER_OFFSET)
    }

}
