// ============================================================
// scenesystem.kt
// Auto-generated by source2offset; do not edit manually
// ============================================================

package org.kvxd.source2offset.offsets

import org.kvxd.unsafeKt.UnsafeKt
import org.kvxd.unsafeKt.mem.Struct

object ScenesystemSchema {

    /** Fields declared directly by CSSDSEndFrameViewInfo. */
    object CSSDSEndFrameViewInfo {
        const val SCHEMA_NAME: String = "CSSDSEndFrameViewInfo"
        const val m_nViewId: Long = 0x0L // uint64; schema=m_nViewId
        const val m_ViewName: Long = 0x8L // CUtlString; schema=m_ViewName
    }

    class CSSDSEndFrameViewInfoStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_nViewId: ULong by uint64(CSSDSEndFrameViewInfo.m_nViewId)
        var m_ViewName: Long by ptr64(CSSDSEndFrameViewInfo.m_ViewName)
    }

    /** Fields declared directly by CSSDSMsg_EndFrame. */
    object CSSDSMsg_EndFrame {
        const val SCHEMA_NAME: String = "CSSDSMsg_EndFrame"
        const val m_Views: Long = 0x0L // CUtlVector<CSSDSEndFrameViewInfo>; schema=m_Views
    }

    class CSSDSMsg_EndFrameStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_Views: CUtlVector<CSSDSEndFrameViewInfo>; no safe value decoder was proven. */
        val m_ViewsAddress: Long get() = base + CSSDSMsg_EndFrame.m_Views
    }

    /** Fields declared directly by CSSDSMsg_LayerBase. */
    object CSSDSMsg_LayerBase {
        const val SCHEMA_NAME: String = "CSSDSMsg_LayerBase"
        const val m_viewId: Long = 0x0L // SceneViewId_t; schema=m_viewId
        const val m_ViewName: Long = 0x10L // CUtlString; schema=m_ViewName
        const val m_nLayerId: Long = 0x18L // uint64; schema=m_nLayerId
        const val m_LayerName: Long = 0x20L // CUtlString; schema=m_LayerName
        const val m_displayText: Long = 0x28L // CUtlString; schema=m_displayText
    }

    class CSSDSMsg_LayerBaseStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Embedded reflected value: SceneViewId_t. */
        val m_viewId: ScenesystemSchema.SceneViewId_tStruct
            get() = ScenesystemSchema.SceneViewId_tStruct(base + CSSDSMsg_LayerBase.m_viewId, mem)
        var m_ViewName: Long by ptr64(CSSDSMsg_LayerBase.m_ViewName)
        var m_nLayerId: ULong by uint64(CSSDSMsg_LayerBase.m_nLayerId)
        var m_LayerName: Long by ptr64(CSSDSMsg_LayerBase.m_LayerName)
        var m_displayText: Long by ptr64(CSSDSMsg_LayerBase.m_displayText)
    }

    /** Fields declared directly by CSSDSMsg_PostLayer. Reflected parent: CSSDSMsg_LayerBase. */
    object CSSDSMsg_PostLayer {
        const val SCHEMA_NAME: String = "CSSDSMsg_PostLayer"
        const val PARENT_SCHEMA_NAME: String = "CSSDSMsg_LayerBase"
    }

    class CSSDSMsg_PostLayerStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by CSSDSMsg_PreLayer. Reflected parent: CSSDSMsg_LayerBase. */
    object CSSDSMsg_PreLayer {
        const val SCHEMA_NAME: String = "CSSDSMsg_PreLayer"
        const val PARENT_SCHEMA_NAME: String = "CSSDSMsg_LayerBase"
    }

    class CSSDSMsg_PreLayerStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by CSSDSMsg_ViewRender. */
    object CSSDSMsg_ViewRender {
        const val SCHEMA_NAME: String = "CSSDSMsg_ViewRender"
        const val m_viewId: Long = 0x0L // SceneViewId_t; schema=m_viewId
        const val m_ViewName: Long = 0x10L // CUtlString; schema=m_ViewName
    }

    class CSSDSMsg_ViewRenderStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Embedded reflected value: SceneViewId_t. */
        val m_viewId: ScenesystemSchema.SceneViewId_tStruct
            get() = ScenesystemSchema.SceneViewId_tStruct(base + CSSDSMsg_ViewRender.m_viewId, mem)
        var m_ViewName: Long by ptr64(CSSDSMsg_ViewRender.m_ViewName)
    }

    /** Fields declared directly by CSSDSMsg_ViewTarget. */
    object CSSDSMsg_ViewTarget {
        const val SCHEMA_NAME: String = "CSSDSMsg_ViewTarget"
        const val m_Name: Long = 0x0L // CUtlString; schema=m_Name
        const val m_TextureId: Long = 0x8L // uint64; schema=m_TextureId
        const val m_nWidth: Long = 0x10L // int32; schema=m_nWidth
        const val m_nHeight: Long = 0x14L // int32; schema=m_nHeight
        const val m_nRequestedWidth: Long = 0x18L // int32; schema=m_nRequestedWidth
        const val m_nRequestedHeight: Long = 0x1CL // int32; schema=m_nRequestedHeight
        const val m_nNumMipLevels: Long = 0x20L // int32; schema=m_nNumMipLevels
        const val m_nDepth: Long = 0x24L // int32; schema=m_nDepth
        const val m_nMultisampleNumSamples: Long = 0x28L // int32; schema=m_nMultisampleNumSamples
        const val m_nFormat: Long = 0x2CL // int32; schema=m_nFormat
    }

    class CSSDSMsg_ViewTargetStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_Name: Long by ptr64(CSSDSMsg_ViewTarget.m_Name)
        var m_TextureId: ULong by uint64(CSSDSMsg_ViewTarget.m_TextureId)
        var m_nWidth: Int by int32(CSSDSMsg_ViewTarget.m_nWidth)
        var m_nHeight: Int by int32(CSSDSMsg_ViewTarget.m_nHeight)
        var m_nRequestedWidth: Int by int32(CSSDSMsg_ViewTarget.m_nRequestedWidth)
        var m_nRequestedHeight: Int by int32(CSSDSMsg_ViewTarget.m_nRequestedHeight)
        var m_nNumMipLevels: Int by int32(CSSDSMsg_ViewTarget.m_nNumMipLevels)
        var m_nDepth: Int by int32(CSSDSMsg_ViewTarget.m_nDepth)
        var m_nMultisampleNumSamples: Int by int32(CSSDSMsg_ViewTarget.m_nMultisampleNumSamples)
        var m_nFormat: Int by int32(CSSDSMsg_ViewTarget.m_nFormat)
    }

    /** Fields declared directly by CSSDSMsg_ViewTargetList. */
    object CSSDSMsg_ViewTargetList {
        const val SCHEMA_NAME: String = "CSSDSMsg_ViewTargetList"
        const val m_viewId: Long = 0x0L // SceneViewId_t; schema=m_viewId
        const val m_ViewName: Long = 0x10L // CUtlString; schema=m_ViewName
        const val m_Targets: Long = 0x18L // CUtlVector<CSSDSMsg_ViewTarget>; schema=m_Targets
    }

    class CSSDSMsg_ViewTargetListStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Embedded reflected value: SceneViewId_t. */
        val m_viewId: ScenesystemSchema.SceneViewId_tStruct
            get() = ScenesystemSchema.SceneViewId_tStruct(base + CSSDSMsg_ViewTargetList.m_viewId, mem)
        var m_ViewName: Long by ptr64(CSSDSMsg_ViewTargetList.m_ViewName)
        /** Raw address of m_Targets: CUtlVector<CSSDSMsg_ViewTarget>; no safe value decoder was proven. */
        val m_TargetsAddress: Long get() = base + CSSDSMsg_ViewTargetList.m_Targets
    }

    /** Fields declared directly by SceneViewId_t. */
    object SceneViewId_t {
        const val SCHEMA_NAME: String = "SceneViewId_t"
        const val m_nViewId: Long = 0x0L // uint64; schema=m_nViewId
        const val m_nFrameCount: Long = 0x8L // uint64; schema=m_nFrameCount
    }

    class SceneViewId_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_nViewId: ULong by uint64(SceneViewId_t.m_nViewId)
        var m_nFrameCount: ULong by uint64(SceneViewId_t.m_nFrameCount)
    }

    object Enums {
        object ESceneViewDebugOverlaysListenerDataType_t {
            const val SCHEMA_NAME: String = "ESceneViewDebugOverlaysListenerDataType_t"
            const val k_ESceneViewDebugOverlaysListenerDataType_BoxAngles: Long = 3L
            const val k_ESceneViewDebugOverlaysListenerDataType_Capsule: Long = 2L
            const val k_ESceneViewDebugOverlaysListenerDataType_Line: Long = 4L
            const val k_ESceneViewDebugOverlaysListenerDataType_SolidBoxAngles: Long = 5L
            const val k_ESceneViewDebugOverlaysListenerDataType_Sphere: Long = 1L
            const val k_ESceneViewDebugOverlaysListenerDataType_Text3D: Long = 6L
            const val k_ESceneViewDebugOverlaysListenerDataType_Unknown: Long = 0L
        }

    }
}
