// ============================================================
// schemasystem.kt
// Auto-generated by source2offset; do not edit manually
// ============================================================

package org.kvxd.source2offset.offsets

import org.kvxd.unsafeKt.UnsafeKt
import org.kvxd.unsafeKt.mem.Struct

object SchemasystemSchema {

    /** Fields declared directly by CExampleSchemaVData_Monomorphic. */
    object CExampleSchemaVData_Monomorphic {
        const val SCHEMA_NAME: String = "CExampleSchemaVData_Monomorphic"
        const val m_nExample1: Long = 0x0L // int32; schema=m_nExample1
        const val m_nExample2: Long = 0x4L // int32; schema=m_nExample2
    }

    class CExampleSchemaVData_MonomorphicStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_nExample1: Int by int32(CExampleSchemaVData_Monomorphic.m_nExample1)
        var m_nExample2: Int by int32(CExampleSchemaVData_Monomorphic.m_nExample2)
    }

    /** Fields declared directly by CExampleSchemaVData_PolymorphicBase. */
    object CExampleSchemaVData_PolymorphicBase {
        const val SCHEMA_NAME: String = "CExampleSchemaVData_PolymorphicBase"
        const val m_nBase: Long = 0x8L // int32; schema=m_nBase
    }

    class CExampleSchemaVData_PolymorphicBaseStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_nBase: Int by int32(CExampleSchemaVData_PolymorphicBase.m_nBase)
    }

    /** Fields declared directly by CExampleSchemaVData_PolymorphicDerivedA. Reflected parent: CExampleSchemaVData_PolymorphicBase. */
    object CExampleSchemaVData_PolymorphicDerivedA {
        const val SCHEMA_NAME: String = "CExampleSchemaVData_PolymorphicDerivedA"
        const val PARENT_SCHEMA_NAME: String = "CExampleSchemaVData_PolymorphicBase"
        const val m_nDerivedA: Long = 0xCL // int32; schema=m_nDerivedA
    }

    class CExampleSchemaVData_PolymorphicDerivedAStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_nDerivedA: Int by int32(CExampleSchemaVData_PolymorphicDerivedA.m_nDerivedA)
    }

    /** Fields declared directly by CExampleSchemaVData_PolymorphicDerivedB. Reflected parent: CExampleSchemaVData_PolymorphicBase. */
    object CExampleSchemaVData_PolymorphicDerivedB {
        const val SCHEMA_NAME: String = "CExampleSchemaVData_PolymorphicDerivedB"
        const val PARENT_SCHEMA_NAME: String = "CExampleSchemaVData_PolymorphicBase"
        const val m_nDerivedB: Long = 0xCL // int32; schema=m_nDerivedB
    }

    class CExampleSchemaVData_PolymorphicDerivedBStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_nDerivedB: Int by int32(CExampleSchemaVData_PolymorphicDerivedB.m_nDerivedB)
    }

    /** Fields declared directly by CSchemaSystemInternalRegistration. */
    object CSchemaSystemInternalRegistration {
        const val SCHEMA_NAME: String = "CSchemaSystemInternalRegistration"
        const val m_Vector2D: Long = 0x0L // Vector2D; schema=m_Vector2D
        const val m_Vector: Long = 0x8L // Vector; schema=m_Vector
        const val m_VectorWS: Long = 0x14L // VectorWS; schema=m_VectorWS
        const val m_VectorAligned: Long = 0x20L // VectorAligned; schema=m_VectorAligned
        const val m_Quaternion: Long = 0x30L // Quaternion; schema=m_Quaternion
        const val m_QAngle: Long = 0x40L // QAngle; schema=m_QAngle
        const val m_RotationVector: Long = 0x4CL // RotationVector; schema=m_RotationVector
        const val m_RadianEuler: Long = 0x58L // RadianEuler; schema=m_RadianEuler
        const val m_DegreeEuler: Long = 0x64L // DegreeEuler; schema=m_DegreeEuler
        const val m_QuaternionStorage: Long = 0x70L // QuaternionStorage; schema=m_QuaternionStorage
        const val m_matrix3x4_t: Long = 0x80L // matrix3x4_t; schema=m_matrix3x4_t
        const val m_matrix3x4a_t: Long = 0xB0L // matrix3x4a_t; schema=m_matrix3x4a_t
        const val m_Color: Long = 0xE0L // Color; schema=m_Color
        const val m_Vector4D: Long = 0xE4L // Vector4D; schema=m_Vector4D
        const val m_CTransform: Long = 0x100L // CTransform; schema=m_CTransform
        const val m_pKeyValues: Long = 0x120L // KeyValues*; schema=m_pKeyValues
        const val m_CUtlBinaryBlock: Long = 0x128L // CUtlBinaryBlock; schema=m_CUtlBinaryBlock
        const val m_CUtlString: Long = 0x138L // CUtlString; schema=m_CUtlString
        const val m_CUtlSymbol: Long = 0x140L // CUtlSymbol; schema=m_CUtlSymbol
        const val m_stringToken: Long = 0x144L // CUtlStringToken; schema=m_stringToken
        const val m_stringTokenWithStorage: Long = 0x148L // CUtlStringTokenWithStorage; schema=m_stringTokenWithStorage
        const val m_ResourceTypes: Long = 0x160L // CResourceArray<CResourcePointer<CResourceString>>; schema=m_ResourceTypes
        const val m_KV3: Long = 0x168L // KeyValues3; schema=m_KV3
    }

    class CSchemaSystemInternalRegistrationStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_Vector2D: Vector2D; no safe value decoder was proven. */
        val m_Vector2DAddress: Long get() = base + CSchemaSystemInternalRegistration.m_Vector2D
        /** Raw address of m_Vector: Vector; no safe value decoder was proven. */
        val m_VectorAddress: Long get() = base + CSchemaSystemInternalRegistration.m_Vector
        /** Raw address of m_VectorWS: VectorWS; no safe value decoder was proven. */
        val m_VectorWSAddress: Long get() = base + CSchemaSystemInternalRegistration.m_VectorWS
        /** Raw address of m_VectorAligned: VectorAligned; no safe value decoder was proven. */
        val m_VectorAlignedAddress: Long get() = base + CSchemaSystemInternalRegistration.m_VectorAligned
        /** Raw address of m_Quaternion: Quaternion; no safe value decoder was proven. */
        val m_QuaternionAddress: Long get() = base + CSchemaSystemInternalRegistration.m_Quaternion
        /** Raw address of m_QAngle: QAngle; no safe value decoder was proven. */
        val m_QAngleAddress: Long get() = base + CSchemaSystemInternalRegistration.m_QAngle
        /** Raw address of m_RotationVector: RotationVector; no safe value decoder was proven. */
        val m_RotationVectorAddress: Long get() = base + CSchemaSystemInternalRegistration.m_RotationVector
        /** Raw address of m_RadianEuler: RadianEuler; no safe value decoder was proven. */
        val m_RadianEulerAddress: Long get() = base + CSchemaSystemInternalRegistration.m_RadianEuler
        /** Raw address of m_DegreeEuler: DegreeEuler; no safe value decoder was proven. */
        val m_DegreeEulerAddress: Long get() = base + CSchemaSystemInternalRegistration.m_DegreeEuler
        /** Raw address of m_QuaternionStorage: QuaternionStorage; no safe value decoder was proven. */
        val m_QuaternionStorageAddress: Long get() = base + CSchemaSystemInternalRegistration.m_QuaternionStorage
        /** Raw address of m_matrix3x4_t: matrix3x4_t; no safe value decoder was proven. */
        val m_matrix3x4_tAddress: Long get() = base + CSchemaSystemInternalRegistration.m_matrix3x4_t
        /** Raw address of m_matrix3x4a_t: matrix3x4a_t; no safe value decoder was proven. */
        val m_matrix3x4a_tAddress: Long get() = base + CSchemaSystemInternalRegistration.m_matrix3x4a_t
        var m_Color: Int by int32(CSchemaSystemInternalRegistration.m_Color)
        /** Raw address of m_Vector4D: Vector4D; no safe value decoder was proven. */
        val m_Vector4DAddress: Long get() = base + CSchemaSystemInternalRegistration.m_Vector4D
        /** Raw address of m_CTransform: CTransform; no safe value decoder was proven. */
        val m_CTransformAddress: Long get() = base + CSchemaSystemInternalRegistration.m_CTransform
        var m_pKeyValues: Long by ptr64(CSchemaSystemInternalRegistration.m_pKeyValues)
        /** Raw address of m_CUtlBinaryBlock: CUtlBinaryBlock; no safe value decoder was proven. */
        val m_CUtlBinaryBlockAddress: Long get() = base + CSchemaSystemInternalRegistration.m_CUtlBinaryBlock
        var m_CUtlString: Long by ptr64(CSchemaSystemInternalRegistration.m_CUtlString)
        /** Raw address of m_CUtlSymbol: CUtlSymbol; no safe value decoder was proven. */
        val m_CUtlSymbolAddress: Long get() = base + CSchemaSystemInternalRegistration.m_CUtlSymbol
        /** Raw address of m_stringToken: CUtlStringToken; no safe value decoder was proven. */
        val m_stringTokenAddress: Long get() = base + CSchemaSystemInternalRegistration.m_stringToken
        /** Raw address of m_stringTokenWithStorage: CUtlStringTokenWithStorage; no safe value decoder was proven. */
        val m_stringTokenWithStorageAddress: Long get() = base + CSchemaSystemInternalRegistration.m_stringTokenWithStorage
        /** Raw address of m_ResourceTypes: CResourceArray<CResourcePointer<CResourceString>>; no safe value decoder was proven. */
        val m_ResourceTypesAddress: Long get() = base + CSchemaSystemInternalRegistration.m_ResourceTypes
        /** Raw address of m_KV3: KeyValues3; no safe value decoder was proven. */
        val m_KV3Address: Long get() = base + CSchemaSystemInternalRegistration.m_KV3
    }

    /** Fields declared directly by InfoForResourceTypeCResourceManifestInternal. */
    object InfoForResourceTypeCResourceManifestInternal {
        const val SCHEMA_NAME: String = "InfoForResourceTypeCResourceManifestInternal"
    }

    class InfoForResourceTypeCResourceManifestInternalStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by ResourceId_t. */
    object ResourceId_t {
        const val SCHEMA_NAME: String = "ResourceId_t"
        const val m_Value: Long = 0x0L // uint64; schema=m_Value
    }

    class ResourceId_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_Value: ULong by uint64(ResourceId_t.m_Value)
    }

    object Enums {
        object fieldtype_t {
            const val SCHEMA_NAME: String = "fieldtype_t"
            const val FIELD_AI_SCHEDULE_BITS: Long = 69L
            const val FIELD_AMMO_INDEX: Long = 67L
            const val FIELD_ATTACHMENT_HANDLE: Long = 66L
            const val FIELD_BOOLEAN: Long = 6L
            const val FIELD_CHARACTER: Long = 8L
            const val FIELD_CLASSPTR: Long = 12L
            const val FIELD_CMOTIONTRANSFORM: Long = 64L
            const val FIELD_CMOTIONTRANSFORM_WORLDSPACE: Long = 65L
            const val FIELD_COLOR32: Long = 9L
            const val FIELD_CONDITION_ID: Long = 68L
            const val FIELD_CSTRING: Long = 30L
            const val FIELD_CTRANSFORM: Long = 59L
            const val FIELD_CTRANSFORM_WORLDSPACE: Long = 60L
            const val FIELD_CUSTOM: Long = 11L
            const val FIELD_DIRECTION_VECTOR_WORLDSPACE: Long = 45L
            const val FIELD_EHANDLE: Long = 13L
            const val FIELD_EMBEDDED: Long = 10L
            const val FIELD_ENGINE_TICK: Long = 77L
            const val FIELD_ENGINE_TIME: Long = 76L
            const val FIELD_FLOAT32: Long = 1L
            const val FIELD_FLOAT64: Long = 34L
            const val FIELD_FUNCTION: Long = 19L
            const val FIELD_GLOBALSYMBOL: Long = 79L
            const val FIELD_HMATERIAL: Long = 41L
            const val FIELD_HMODEL: Long = 42L
            const val FIELD_HNMGRAPHDEFINITION: Long = 80L
            const val FIELD_HPARTICLESYSTEMDEFINITION: Long = 56L
            const val FIELD_HPOSTPROCESSING: Long = 61L
            const val FIELD_HRENDERTEXTURE: Long = 55L
            const val FIELD_HSCRIPT: Long = 31L
            const val FIELD_HSCRIPT_LIGHTBINDING: Long = 48L
            const val FIELD_HSCRIPT_NEW_INSTANCE: Long = 36L
            const val FIELD_HVDATA: Long = 73L
            const val FIELD_INPUT: Long = 18L
            const val FIELD_INT16: Long = 7L
            const val FIELD_INT32: Long = 5L
            const val FIELD_INT64: Long = 26L
            const val FIELD_INTERVAL: Long = 23L
            const val FIELD_MATRIX3X4: Long = 62L
            const val FIELD_MATRIX3X4_WORLDSPACE: Long = 22L
            const val FIELD_MODIFIER_HANDLE: Long = 70L
            const val FIELD_NETWORK_ORIGIN_CELL_QUANTIZED_POSITION_VECTOR: Long = 54L
            const val FIELD_NETWORK_ORIGIN_CELL_QUANTIZED_VECTOR: Long = 40L
            const val FIELD_NETWORK_QUANTIZED_FLOAT: Long = 44L
            const val FIELD_NETWORK_QUANTIZED_VECTOR: Long = 43L
            const val FIELD_POSITION_VECTOR: Long = 14L
            const val FIELD_POSITIVEINTEGER_OR_NULL: Long = 35L
            const val FIELD_QANGLE: Long = 39L
            const val FIELD_QANGLE_WORLDSPACE: Long = 46L
            const val FIELD_QUATERNION: Long = 4L
            const val FIELD_QUATERNION_WORLDSPACE: Long = 47L
            const val FIELD_RESOURCE: Long = 28L
            const val FIELD_ROTATION_VECTOR: Long = 71L
            const val FIELD_ROTATION_VECTOR_WORLDSPACE: Long = 72L
            const val FIELD_SCALE32: Long = 74L
            const val FIELD_SHIM: Long = 63L
            const val FIELD_SOUNDNAME: Long = 17L
            const val FIELD_STRING: Long = 2L
            const val FIELD_STRING_AND_TOKEN: Long = 75L
            const val FIELD_TICK: Long = 16L
            const val FIELD_TIME: Long = 15L
            const val FIELD_TYPECOUNT: Long = 81L
            const val FIELD_TYPEUNKNOWN: Long = 29L
            const val FIELD_UINT16: Long = 58L
            const val FIELD_UINT32: Long = 37L
            const val FIELD_UINT64: Long = 33L
            const val FIELD_UINT8: Long = 57L
            const val FIELD_UNUSED: Long = 24L
            const val FIELD_UTLSTRING: Long = 53L
            const val FIELD_UTLSTRINGTOKEN: Long = 38L
            const val FIELD_V8_ARRAY: Long = 51L
            const val FIELD_V8_CALLBACK_INFO: Long = 52L
            const val FIELD_V8_OBJECT: Long = 50L
            const val FIELD_V8_VALUE: Long = 49L
            const val FIELD_VARIANT: Long = 32L
            const val FIELD_VECTOR: Long = 3L
            const val FIELD_VECTOR2D: Long = 25L
            const val FIELD_VECTOR4D: Long = 27L
            const val FIELD_VMATRIX: Long = 20L
            const val FIELD_VMATRIX_WORLDSPACE: Long = 21L
            const val FIELD_VOID: Long = 0L
            const val FIELD_WORLD_GROUP_ID: Long = 78L
        }

    }
}
