// ============================================================
// steamaudio.kt
// Auto-generated by source2offset; do not edit manually
// ============================================================

package org.kvxd.source2offset.offsets

import org.kvxd.unsafeKt.UnsafeKt
import org.kvxd.unsafeKt.mem.Struct

/**
 * Reflected schema data for libsteamaudio.so.
 *
 * Offset namespaces contain fields declared directly on each reflected class.
 * Struct wrappers deliberately do not inherit: the dump proves parent relationships,
 * but does not assume a universal native base-subobject displacement rule.
 * Fields with unknown value layout retain an Address accessor instead of an unsafe decoder.
 */
object SteamaudioSchema {

    /** Fields declared directly by CSteamAudioAmbisonicsField. */
    object CSteamAudioAmbisonicsField {
        const val SCHEMA_NAME: String = "CSteamAudioAmbisonicsField"
        const val m_field: Long = 0x0L // CUtlVector<float32>; schema=m_field
    }

    /** Read/write view of decodable fields declared directly by CSteamAudioAmbisonicsField.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CSteamAudioAmbisonicsFieldStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_field: CUtlVector<float32>; no safe value decoder was proven. */
        val m_fieldAddress: Long get() = base + CSteamAudioAmbisonicsField.m_field
    }

    /** Fields declared directly by CSteamAudioBakedDimensionsData. */
    object CSteamAudioBakedDimensionsData {
        const val SCHEMA_NAME: String = "CSteamAudioBakedDimensionsData"
        const val m_settings: Long = 0x0L // SteamAudioCustomDataDimensionsSettings_t; schema=m_settings
        const val m_probes: Long = 0x18L // CSteamAudioProbeData; schema=m_probes
        const val m_vecInOut: Long = 0x20L // CUtlVector<float32>; schema=m_vecInOut
        const val m_vecSize: Long = 0x38L // CUtlVector<float32>; schema=m_vecSize
        const val m_vecOutsideField: Long = 0x50L // CUtlVector<CSteamAudioAmbisonicsField>; schema=m_vecOutsideField
        const val m_vecInsideSmallSizeField: Long = 0x68L // CUtlVector<CSteamAudioAmbisonicsField>; schema=m_vecInsideSmallSizeField
        const val m_movables: Long = 0x80L // CSteamAudioMovableBakedData<CSteamAudioBakedDimensionsData>; schema=m_movables
    }

    /** Read/write view of decodable fields declared directly by CSteamAudioBakedDimensionsData.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CSteamAudioBakedDimensionsDataStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Embedded reflected value: SteamAudioCustomDataDimensionsSettings_t. */
        val m_settings: SteamaudioSchema.SteamAudioCustomDataDimensionsSettings_tStruct
            get() = SteamaudioSchema.SteamAudioCustomDataDimensionsSettings_tStruct(base + CSteamAudioBakedDimensionsData.m_settings, mem)
        /** Embedded reflected value: CSteamAudioProbeData. */
        val m_probes: SteamaudioSchema.CSteamAudioProbeDataStruct
            get() = SteamaudioSchema.CSteamAudioProbeDataStruct(base + CSteamAudioBakedDimensionsData.m_probes, mem)
        /** Raw address of m_vecInOut: CUtlVector<float32>; no safe value decoder was proven. */
        val m_vecInOutAddress: Long get() = base + CSteamAudioBakedDimensionsData.m_vecInOut
        /** Raw address of m_vecSize: CUtlVector<float32>; no safe value decoder was proven. */
        val m_vecSizeAddress: Long get() = base + CSteamAudioBakedDimensionsData.m_vecSize
        /** Raw address of m_vecOutsideField: CUtlVector<CSteamAudioAmbisonicsField>; no safe value decoder was proven. */
        val m_vecOutsideFieldAddress: Long get() = base + CSteamAudioBakedDimensionsData.m_vecOutsideField
        /** Raw address of m_vecInsideSmallSizeField: CUtlVector<CSteamAudioAmbisonicsField>; no safe value decoder was proven. */
        val m_vecInsideSmallSizeFieldAddress: Long get() = base + CSteamAudioBakedDimensionsData.m_vecInsideSmallSizeField
        /** Raw address of m_movables: CSteamAudioMovableBakedData<CSteamAudioBakedDimensionsData>; no safe value decoder was proven. */
        val m_movablesAddress: Long get() = base + CSteamAudioBakedDimensionsData.m_movables
    }

    /** Fields declared directly by CSteamAudioBakedMaterialsData. */
    object CSteamAudioBakedMaterialsData {
        const val SCHEMA_NAME: String = "CSteamAudioBakedMaterialsData"
        const val m_probes: Long = 0x0L // CSteamAudioProbeData; schema=m_probes
        const val m_vecMaterialTokens: Long = 0x8L // CUtlVector<uint32>; schema=m_vecMaterialTokens
        const val m_vecMaterialWeights: Long = 0x20L // CUtlVector<float32>; schema=m_vecMaterialWeights
    }

    /** Read/write view of decodable fields declared directly by CSteamAudioBakedMaterialsData.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CSteamAudioBakedMaterialsDataStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Embedded reflected value: CSteamAudioProbeData. */
        val m_probes: SteamaudioSchema.CSteamAudioProbeDataStruct
            get() = SteamaudioSchema.CSteamAudioProbeDataStruct(base + CSteamAudioBakedMaterialsData.m_probes, mem)
        /** Raw address of m_vecMaterialTokens: CUtlVector<uint32>; no safe value decoder was proven. */
        val m_vecMaterialTokensAddress: Long get() = base + CSteamAudioBakedMaterialsData.m_vecMaterialTokens
        /** Raw address of m_vecMaterialWeights: CUtlVector<float32>; no safe value decoder was proven. */
        val m_vecMaterialWeightsAddress: Long get() = base + CSteamAudioBakedMaterialsData.m_vecMaterialWeights
    }

    /** Fields declared directly by CSteamAudioBakedOcclusionData. */
    object CSteamAudioBakedOcclusionData {
        const val SCHEMA_NAME: String = "CSteamAudioBakedOcclusionData"
        const val m_settings: Long = 0x0L // SteamAudioCustomDataOcclusionSettings_t; schema=m_settings
        const val m_probes: Long = 0x10L // CSteamAudioProbeData; schema=m_probes
        const val m_vecPathingRatio: Long = 0x18L // CUtlVector<float32>; schema=m_vecPathingRatio
        const val m_vecPathingDeviation: Long = 0x30L // CUtlVector<float32>; schema=m_vecPathingDeviation
        const val m_vecReflectionRatio: Long = 0x48L // CUtlVector<float32>; schema=m_vecReflectionRatio
    }

    /** Read/write view of decodable fields declared directly by CSteamAudioBakedOcclusionData.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CSteamAudioBakedOcclusionDataStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Embedded reflected value: SteamAudioCustomDataOcclusionSettings_t. */
        val m_settings: SteamaudioSchema.SteamAudioCustomDataOcclusionSettings_tStruct
            get() = SteamaudioSchema.SteamAudioCustomDataOcclusionSettings_tStruct(base + CSteamAudioBakedOcclusionData.m_settings, mem)
        /** Embedded reflected value: CSteamAudioProbeData. */
        val m_probes: SteamaudioSchema.CSteamAudioProbeDataStruct
            get() = SteamaudioSchema.CSteamAudioProbeDataStruct(base + CSteamAudioBakedOcclusionData.m_probes, mem)
        /** Raw address of m_vecPathingRatio: CUtlVector<float32>; no safe value decoder was proven. */
        val m_vecPathingRatioAddress: Long get() = base + CSteamAudioBakedOcclusionData.m_vecPathingRatio
        /** Raw address of m_vecPathingDeviation: CUtlVector<float32>; no safe value decoder was proven. */
        val m_vecPathingDeviationAddress: Long get() = base + CSteamAudioBakedOcclusionData.m_vecPathingDeviation
        /** Raw address of m_vecReflectionRatio: CUtlVector<float32>; no safe value decoder was proven. */
        val m_vecReflectionRatioAddress: Long get() = base + CSteamAudioBakedOcclusionData.m_vecReflectionRatio
    }

    /** Fields declared directly by CSteamAudioBakedPathingData. */
    object CSteamAudioBakedPathingData {
        const val SCHEMA_NAME: String = "CSteamAudioBakedPathingData"
        const val m_nBands: Long = 0x0L // int32; schema=m_nBands
        const val m_probes: Long = 0x8L // CSteamAudioProbeData; schema=m_probes
        const val m_movables: Long = 0x10L // CSteamAudioMovableBakedData<CSteamAudioBakedPathingData>; schema=m_movables
    }

    /** Read/write view of decodable fields declared directly by CSteamAudioBakedPathingData.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CSteamAudioBakedPathingDataStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_nBands: Int by int32(CSteamAudioBakedPathingData.m_nBands)
        /** Embedded reflected value: CSteamAudioProbeData. */
        val m_probes: SteamaudioSchema.CSteamAudioProbeDataStruct
            get() = SteamaudioSchema.CSteamAudioProbeDataStruct(base + CSteamAudioBakedPathingData.m_probes, mem)
        /** Raw address of m_movables: CSteamAudioMovableBakedData<CSteamAudioBakedPathingData>; no safe value decoder was proven. */
        val m_movablesAddress: Long get() = base + CSteamAudioBakedPathingData.m_movables
    }

    /** Fields declared directly by CSteamAudioBakedReverbData. */
    object CSteamAudioBakedReverbData {
        const val SCHEMA_NAME: String = "CSteamAudioBakedReverbData"
        const val m_nBands: Long = 0x0L // int32; schema=m_nBands
        const val m_scene: Long = 0x8L // CSteamAudioSceneData; schema=m_scene
        const val m_probes: Long = 0x18L // CSteamAudioProbeData; schema=m_probes
        const val m_grid: Long = 0x20L // CSteamAudioProbeGrid; schema=m_grid
        const val m_reverbSettings: Long = 0x78L // SteamAudioReverbSettings_t; schema=m_reverbSettings
        const val m_reverbClusteringSettings: Long = 0x8CL // SteamAudioReverbClusteringSettings_t; schema=m_reverbClusteringSettings
        const val m_reverbCompressionSettings: Long = 0x98L // SteamAudioReverbCompressionSettings_t; schema=m_reverbCompressionSettings
        const val m_clusteredProbes: Long = 0xA0L // CSteamAudioProbeData; schema=m_clusteredProbes
        const val m_vecClusterForProbe: Long = 0xA8L // CUtlVector<int16>; schema=m_vecClusterForProbe
        const val m_compressedData: Long = 0xC0L // CSteamAudioCompressedReverb; schema=m_compressedData
        const val m_compressedClusteredData: Long = 0x120L // CSteamAudioCompressedReverb; schema=m_compressedClusteredData
        const val m_movables: Long = 0x180L // CSteamAudioMovableBakedData<CSteamAudioBakedReverbData>; schema=m_movables
    }

    /** Read/write view of decodable fields declared directly by CSteamAudioBakedReverbData.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CSteamAudioBakedReverbDataStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_nBands: Int by int32(CSteamAudioBakedReverbData.m_nBands)
        /** Embedded reflected value: CSteamAudioSceneData. */
        val m_scene: SteamaudioSchema.CSteamAudioSceneDataStruct
            get() = SteamaudioSchema.CSteamAudioSceneDataStruct(base + CSteamAudioBakedReverbData.m_scene, mem)
        /** Embedded reflected value: CSteamAudioProbeData. */
        val m_probes: SteamaudioSchema.CSteamAudioProbeDataStruct
            get() = SteamaudioSchema.CSteamAudioProbeDataStruct(base + CSteamAudioBakedReverbData.m_probes, mem)
        /** Embedded reflected value: CSteamAudioProbeGrid. */
        val m_grid: SteamaudioSchema.CSteamAudioProbeGridStruct
            get() = SteamaudioSchema.CSteamAudioProbeGridStruct(base + CSteamAudioBakedReverbData.m_grid, mem)
        /** Embedded reflected value: SteamAudioReverbSettings_t. */
        val m_reverbSettings: SteamaudioSchema.SteamAudioReverbSettings_tStruct
            get() = SteamaudioSchema.SteamAudioReverbSettings_tStruct(base + CSteamAudioBakedReverbData.m_reverbSettings, mem)
        /** Embedded reflected value: SteamAudioReverbClusteringSettings_t. */
        val m_reverbClusteringSettings: SteamaudioSchema.SteamAudioReverbClusteringSettings_tStruct
            get() = SteamaudioSchema.SteamAudioReverbClusteringSettings_tStruct(base + CSteamAudioBakedReverbData.m_reverbClusteringSettings, mem)
        /** Embedded reflected value: SteamAudioReverbCompressionSettings_t. */
        val m_reverbCompressionSettings: SteamaudioSchema.SteamAudioReverbCompressionSettings_tStruct
            get() = SteamaudioSchema.SteamAudioReverbCompressionSettings_tStruct(base + CSteamAudioBakedReverbData.m_reverbCompressionSettings, mem)
        /** Embedded reflected value: CSteamAudioProbeData. */
        val m_clusteredProbes: SteamaudioSchema.CSteamAudioProbeDataStruct
            get() = SteamaudioSchema.CSteamAudioProbeDataStruct(base + CSteamAudioBakedReverbData.m_clusteredProbes, mem)
        /** Raw address of m_vecClusterForProbe: CUtlVector<int16>; no safe value decoder was proven. */
        val m_vecClusterForProbeAddress: Long get() = base + CSteamAudioBakedReverbData.m_vecClusterForProbe
        /** Embedded reflected value: CSteamAudioCompressedReverb. */
        val m_compressedData: SteamaudioSchema.CSteamAudioCompressedReverbStruct
            get() = SteamaudioSchema.CSteamAudioCompressedReverbStruct(base + CSteamAudioBakedReverbData.m_compressedData, mem)
        /** Embedded reflected value: CSteamAudioCompressedReverb. */
        val m_compressedClusteredData: SteamaudioSchema.CSteamAudioCompressedReverbStruct
            get() = SteamaudioSchema.CSteamAudioCompressedReverbStruct(base + CSteamAudioBakedReverbData.m_compressedClusteredData, mem)
        /** Raw address of m_movables: CSteamAudioMovableBakedData<CSteamAudioBakedReverbData>; no safe value decoder was proven. */
        val m_movablesAddress: Long get() = base + CSteamAudioBakedReverbData.m_movables
    }

    /** Fields declared directly by CSteamAudioCompressedReverb. */
    object CSteamAudioCompressedReverb {
        const val SCHEMA_NAME: String = "CSteamAudioCompressedReverb"
        const val m_nChannels: Long = 0x0L // int32; schema=m_nChannels
        const val m_nBands: Long = 0x4L // int32; schema=m_nBands
        const val m_nBins: Long = 0x8L // int32; schema=m_nBins
        const val m_nProbes: Long = 0xCL // int32; schema=m_nProbes
        const val m_vecNumSingularValues: Long = 0x10L // CUtlVector<int32>; schema=m_vecNumSingularValues
        const val m_vecDictionary: Long = 0x28L // CUtlVector<float32>; schema=m_vecDictionary
        const val m_vecCompressedData: Long = 0x40L // CUtlVector<float32>; schema=m_vecCompressedData
        const val m_pCompressedData: Long = 0x58L // IPLCompressedEnergyFields; schema=m_pCompressedData
    }

    /** Read/write view of decodable fields declared directly by CSteamAudioCompressedReverb.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CSteamAudioCompressedReverbStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_nChannels: Int by int32(CSteamAudioCompressedReverb.m_nChannels)
        var m_nBands: Int by int32(CSteamAudioCompressedReverb.m_nBands)
        var m_nBins: Int by int32(CSteamAudioCompressedReverb.m_nBins)
        var m_nProbes: Int by int32(CSteamAudioCompressedReverb.m_nProbes)
        /** Raw address of m_vecNumSingularValues: CUtlVector<int32>; no safe value decoder was proven. */
        val m_vecNumSingularValuesAddress: Long get() = base + CSteamAudioCompressedReverb.m_vecNumSingularValues
        /** Raw address of m_vecDictionary: CUtlVector<float32>; no safe value decoder was proven. */
        val m_vecDictionaryAddress: Long get() = base + CSteamAudioCompressedReverb.m_vecDictionary
        /** Raw address of m_vecCompressedData: CUtlVector<float32>; no safe value decoder was proven. */
        val m_vecCompressedDataAddress: Long get() = base + CSteamAudioCompressedReverb.m_vecCompressedData
        /** Raw address of m_pCompressedData: IPLCompressedEnergyFields; no safe value decoder was proven. */
        val m_pCompressedDataAddress: Long get() = base + CSteamAudioCompressedReverb.m_pCompressedData
    }

    /** Fields declared directly by CSteamAudioProbeData. */
    object CSteamAudioProbeData {
        const val SCHEMA_NAME: String = "CSteamAudioProbeData"
        const val m_pProbeBatch: Long = 0x0L // IPLProbeBatch; schema=m_pProbeBatch
    }

    /** Read/write view of decodable fields declared directly by CSteamAudioProbeData.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CSteamAudioProbeDataStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_pProbeBatch: IPLProbeBatch; no safe value decoder was proven. */
        val m_pProbeBatchAddress: Long get() = base + CSteamAudioProbeData.m_pProbeBatch
    }

    /** Fields declared directly by CSteamAudioProbeGrid. */
    object CSteamAudioProbeGrid {
        const val SCHEMA_NAME: String = "CSteamAudioProbeGrid"
        const val m_aabb: Long = 0x0L // AABB_t; schema=m_aabb
        const val m_flSpacing: Long = 0x18L // float32; schema=m_flSpacing
        const val m_nx: Long = 0x1CL // int32; schema=m_nx
        const val m_ny: Long = 0x20L // int32; schema=m_ny
        const val m_nz: Long = 0x24L // int32; schema=m_nz
        const val m_vecLineSegments: Long = 0x28L // CUtlVector<CSteamAudioProbeLineSegment>; schema=m_vecLineSegments
        const val m_vecProbes: Long = 0x40L // CUtlVector<Vector>; schema=m_vecProbes
    }

    /** Read/write view of decodable fields declared directly by CSteamAudioProbeGrid.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CSteamAudioProbeGridStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Embedded reflected value: AABB_t. */
        val m_aabb: ResourcesystemSchema.AABB_tStruct
            get() = ResourcesystemSchema.AABB_tStruct(base + CSteamAudioProbeGrid.m_aabb, mem)
        var m_flSpacing: Float by float(CSteamAudioProbeGrid.m_flSpacing)
        var m_nx: Int by int32(CSteamAudioProbeGrid.m_nx)
        var m_ny: Int by int32(CSteamAudioProbeGrid.m_ny)
        var m_nz: Int by int32(CSteamAudioProbeGrid.m_nz)
        /** Raw address of m_vecLineSegments: CUtlVector<CSteamAudioProbeLineSegment>; no safe value decoder was proven. */
        val m_vecLineSegmentsAddress: Long get() = base + CSteamAudioProbeGrid.m_vecLineSegments
        /** Raw address of m_vecProbes: CUtlVector<Vector>; no safe value decoder was proven. */
        val m_vecProbesAddress: Long get() = base + CSteamAudioProbeGrid.m_vecProbes
    }

    /** Fields declared directly by CSteamAudioProbeLineSegment. */
    object CSteamAudioProbeLineSegment {
        const val SCHEMA_NAME: String = "CSteamAudioProbeLineSegment"
        const val m_vStart: Long = 0x0L // Vector; schema=m_vStart
        const val m_vEnd: Long = 0xCL // Vector; schema=m_vEnd
        const val m_vecIntervals: Long = 0x18L // CUtlVector<float32>; schema=m_vecIntervals
        const val m_vecProbeIndices: Long = 0x30L // CUtlVector<int32>; schema=m_vecProbeIndices
    }

    /** Read/write view of decodable fields declared directly by CSteamAudioProbeLineSegment.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CSteamAudioProbeLineSegmentStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_vStart: Vector; no safe value decoder was proven. */
        val m_vStartAddress: Long get() = base + CSteamAudioProbeLineSegment.m_vStart
        /** Raw address of m_vEnd: Vector; no safe value decoder was proven. */
        val m_vEndAddress: Long get() = base + CSteamAudioProbeLineSegment.m_vEnd
        /** Raw address of m_vecIntervals: CUtlVector<float32>; no safe value decoder was proven. */
        val m_vecIntervalsAddress: Long get() = base + CSteamAudioProbeLineSegment.m_vecIntervals
        /** Raw address of m_vecProbeIndices: CUtlVector<int32>; no safe value decoder was proven. */
        val m_vecProbeIndicesAddress: Long get() = base + CSteamAudioProbeLineSegment.m_vecProbeIndices
    }

    /** Fields declared directly by CSteamAudioSceneData. */
    object CSteamAudioSceneData {
        const val SCHEMA_NAME: String = "CSteamAudioSceneData"
        const val m_pScene: Long = 0x0L // IPLScene; schema=m_pScene
        const val m_pStaticMesh: Long = 0x8L // IPLStaticMesh; schema=m_pStaticMesh
    }

    /** Read/write view of decodable fields declared directly by CSteamAudioSceneData.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class CSteamAudioSceneDataStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        /** Raw address of m_pScene: IPLScene; no safe value decoder was proven. */
        val m_pSceneAddress: Long get() = base + CSteamAudioSceneData.m_pScene
        /** Raw address of m_pStaticMesh: IPLStaticMesh; no safe value decoder was proven. */
        val m_pStaticMeshAddress: Long get() = base + CSteamAudioSceneData.m_pStaticMesh
    }

    /** Fields declared directly by SteamAudioCustomDataDimensionsSettings_t. */
    object SteamAudioCustomDataDimensionsSettings_t {
        const val SCHEMA_NAME: String = "SteamAudioCustomDataDimensionsSettings_t"
        const val m_nAmbisonicsOrderOutsideField: Long = 0x0L // int32; schema=m_nAmbisonicsOrderOutsideField
        const val m_nAmbisonicsOrderInsideSizeField: Long = 0x4L // int32; schema=m_nAmbisonicsOrderInsideSizeField
        const val m_flOutsideThreshold: Long = 0x8L // float32; schema=m_flOutsideThreshold
        const val m_flSizeThreshold: Long = 0xCL // float32; schema=m_flSizeThreshold
        const val m_flInsideThreshold: Long = 0x10L // float32; schema=m_flInsideThreshold
    }

    /** Read/write view of decodable fields declared directly by SteamAudioCustomDataDimensionsSettings_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class SteamAudioCustomDataDimensionsSettings_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_nAmbisonicsOrderOutsideField: Int by int32(SteamAudioCustomDataDimensionsSettings_t.m_nAmbisonicsOrderOutsideField)
        var m_nAmbisonicsOrderInsideSizeField: Int by int32(SteamAudioCustomDataDimensionsSettings_t.m_nAmbisonicsOrderInsideSizeField)
        var m_flOutsideThreshold: Float by float(SteamAudioCustomDataDimensionsSettings_t.m_flOutsideThreshold)
        var m_flSizeThreshold: Float by float(SteamAudioCustomDataDimensionsSettings_t.m_flSizeThreshold)
        var m_flInsideThreshold: Float by float(SteamAudioCustomDataDimensionsSettings_t.m_flInsideThreshold)
    }

    /** Fields declared directly by SteamAudioCustomDataOcclusionSettings_t. */
    object SteamAudioCustomDataOcclusionSettings_t {
        const val SCHEMA_NAME: String = "SteamAudioCustomDataOcclusionSettings_t"
        const val m_bEnablePathing: Long = 0x0L // bool; schema=m_bEnablePathing
        const val m_bEnableReflections: Long = 0x1L // bool; schema=m_bEnableReflections
        const val m_nReflectionRays: Long = 0x4L // int32; schema=m_nReflectionRays
        const val m_nReflectionBounces: Long = 0x8L // int32; schema=m_nReflectionBounces
    }

    /** Read/write view of decodable fields declared directly by SteamAudioCustomDataOcclusionSettings_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class SteamAudioCustomDataOcclusionSettings_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_bEnablePathing: Boolean by bool(SteamAudioCustomDataOcclusionSettings_t.m_bEnablePathing)
        var m_bEnableReflections: Boolean by bool(SteamAudioCustomDataOcclusionSettings_t.m_bEnableReflections)
        var m_nReflectionRays: Int by int32(SteamAudioCustomDataOcclusionSettings_t.m_nReflectionRays)
        var m_nReflectionBounces: Int by int32(SteamAudioCustomDataOcclusionSettings_t.m_nReflectionBounces)
    }

    /** Fields declared directly by SteamAudioPathSettings_t. */
    object SteamAudioPathSettings_t {
        const val SCHEMA_NAME: String = "SteamAudioPathSettings_t"
        const val m_nNumVisSamples: Long = 0x0L // int32; schema=m_nNumVisSamples
        const val m_flProbeVisRadius: Long = 0x4L // float32; schema=m_flProbeVisRadius
        const val m_flProbeVisThreshold: Long = 0x8L // float32; schema=m_flProbeVisThreshold
        const val m_flProbePathRange: Long = 0xCL // float32; schema=m_flProbePathRange
    }

    /** Read/write view of decodable fields declared directly by SteamAudioPathSettings_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class SteamAudioPathSettings_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_nNumVisSamples: Int by int32(SteamAudioPathSettings_t.m_nNumVisSamples)
        var m_flProbeVisRadius: Float by float(SteamAudioPathSettings_t.m_flProbeVisRadius)
        var m_flProbeVisThreshold: Float by float(SteamAudioPathSettings_t.m_flProbeVisThreshold)
        var m_flProbePathRange: Float by float(SteamAudioPathSettings_t.m_flProbePathRange)
    }

    /** Fields declared directly by SteamAudioReverbClusteringSettings_t. */
    object SteamAudioReverbClusteringSettings_t {
        const val SCHEMA_NAME: String = "SteamAudioReverbClusteringSettings_t"
        const val m_bEnableClustering: Long = 0x0L // bool; schema=m_bEnableClustering
        const val m_nCubeMapResolution: Long = 0x4L // int32; schema=m_nCubeMapResolution
        const val m_flDepthThreshold: Long = 0x8L // float32; schema=m_flDepthThreshold
    }

    /** Read/write view of decodable fields declared directly by SteamAudioReverbClusteringSettings_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class SteamAudioReverbClusteringSettings_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_bEnableClustering: Boolean by bool(SteamAudioReverbClusteringSettings_t.m_bEnableClustering)
        var m_nCubeMapResolution: Int by int32(SteamAudioReverbClusteringSettings_t.m_nCubeMapResolution)
        var m_flDepthThreshold: Float by float(SteamAudioReverbClusteringSettings_t.m_flDepthThreshold)
    }

    /** Fields declared directly by SteamAudioReverbCompressionSettings_t. */
    object SteamAudioReverbCompressionSettings_t {
        const val SCHEMA_NAME: String = "SteamAudioReverbCompressionSettings_t"
        const val m_bEnableCompression: Long = 0x0L // bool; schema=m_bEnableCompression
        const val m_flQuality: Long = 0x4L // float32; schema=m_flQuality
    }

    /** Read/write view of decodable fields declared directly by SteamAudioReverbCompressionSettings_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class SteamAudioReverbCompressionSettings_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_bEnableCompression: Boolean by bool(SteamAudioReverbCompressionSettings_t.m_bEnableCompression)
        var m_flQuality: Float by float(SteamAudioReverbCompressionSettings_t.m_flQuality)
    }

    /** Fields declared directly by SteamAudioReverbSettings_t. */
    object SteamAudioReverbSettings_t {
        const val SCHEMA_NAME: String = "SteamAudioReverbSettings_t"
        const val m_nNumRays: Long = 0x0L // int32; schema=m_nNumRays
        const val m_nNumBounces: Long = 0x4L // int32; schema=m_nNumBounces
        const val m_flIRDuration: Long = 0x8L // float32; schema=m_flIRDuration
        const val m_nAmbisonicsOrder: Long = 0xCL // int32; schema=m_nAmbisonicsOrder
        const val m_bExportScene: Long = 0x10L // bool; schema=m_bExportScene
    }

    /** Read/write view of decodable fields declared directly by SteamAudioReverbSettings_t.
     *  Non-decodable fields expose their in-object address without guessing layout. */
    class SteamAudioReverbSettings_tStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_nNumRays: Int by int32(SteamAudioReverbSettings_t.m_nNumRays)
        var m_nNumBounces: Int by int32(SteamAudioReverbSettings_t.m_nNumBounces)
        var m_flIRDuration: Float by float(SteamAudioReverbSettings_t.m_flIRDuration)
        var m_nAmbisonicsOrder: Int by int32(SteamAudioReverbSettings_t.m_nAmbisonicsOrder)
        var m_bExportScene: Boolean by bool(SteamAudioReverbSettings_t.m_bExportScene)
    }

}
