// ============================================================
// worldrenderer.kt
// Auto-generated by source2offset; do not edit manually
// ============================================================

package org.kvxd.source2offset.offsets

import org.kvxd.unsafeKt.UnsafeKt
import org.kvxd.unsafeKt.mem.Struct

object WorldrendererSchema {

    /** Fields declared directly by CEntityComponent. */
    object CEntityComponent {
        const val SCHEMA_NAME: String = "CEntityComponent"
    }

    class CEntityComponentStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        // No directly declared reflected fields.
    }

    /** Fields declared directly by CEntityInstance. */
    object CEntityInstance {
        const val SCHEMA_NAME: String = "CEntityInstance"
        const val m_iszPrivateVScripts: Long = 0x8L // CUtlSymbolLarge; schema=m_iszPrivateVScripts
        const val m_pEntity: Long = 0x10L // CEntityIdentity*; schema=m_pEntity
        const val m_CScriptComponent: Long = 0x28L // CScriptComponent*; schema=m_CScriptComponent
    }

    class CEntityInstanceStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_iszPrivateVScripts: Long by ptr64(CEntityInstance.m_iszPrivateVScripts)
        var m_pEntity: Long by ptr64(CEntityInstance.m_pEntity)
        var m_CScriptComponent: Long by ptr64(CEntityInstance.m_CScriptComponent)
    }

    /** Fields declared directly by CScriptComponent. Reflected parent: CEntityComponent. */
    object CScriptComponent {
        const val SCHEMA_NAME: String = "CScriptComponent"
        const val PARENT_SCHEMA_NAME: String = "CEntityComponent"
        const val m_scriptClassName: Long = 0x30L // CUtlSymbolLarge; schema=m_scriptClassName
    }

    class CScriptComponentStruct(base: Long, mem: UnsafeKt) : Struct(base, mem) {
        var m_scriptClassName: Long by ptr64(CScriptComponent.m_scriptClassName)
    }

    object Enums {
        object RTProxyInstanceFlags_t {
            const val SCHEMA_NAME: String = "RTProxyInstanceFlags_t"
            const val RTPROXY_INSTANCE_FLAG_NONE: Long = 0L
            const val RTPROXY_INSTANCE_UNIQUE_MESH: Long = 1L
        }

    }
}
